// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logging-service.proto

package v2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId               int64                `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TypeId               int64                `protobuf:"varint,3,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Content              string               `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *User) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CREATE
type CreateUserRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindUsersRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	TypeId               int64                `protobuf:"varint,5,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Content              string               `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int32                `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,9,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindUsersRequest) Reset()         { *m = FindUsersRequest{} }
func (m *FindUsersRequest) String() string { return proto.CompactTextString(m) }
func (*FindUsersRequest) ProtoMessage()    {}
func (*FindUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{3}
}

func (m *FindUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUsersRequest.Unmarshal(m, b)
}
func (m *FindUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUsersRequest.Marshal(b, m, deterministic)
}
func (m *FindUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUsersRequest.Merge(m, src)
}
func (m *FindUsersRequest) XXX_Size() int {
	return xxx_messageInfo_FindUsersRequest.Size(m)
}
func (m *FindUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUsersRequest proto.InternalMessageInfo

func (m *FindUsersRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUsersRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindUsersRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindUsersRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FindUsersRequest) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *FindUsersRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindUsersRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindUsersResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount           int64    `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUsersResponse) Reset()         { *m = FindUsersResponse{} }
func (m *FindUsersResponse) String() string { return proto.CompactTextString(m) }
func (*FindUsersResponse) ProtoMessage()    {}
func (*FindUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{4}
}

func (m *FindUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUsersResponse.Unmarshal(m, b)
}
func (m *FindUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUsersResponse.Marshal(b, m, deterministic)
}
func (m *FindUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUsersResponse.Merge(m, src)
}
func (m *FindUsersResponse) XXX_Size() int {
	return xxx_messageInfo_FindUsersResponse.Size(m)
}
func (m *FindUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUsersResponse proto.InternalMessageInfo

func (m *FindUsersResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *FindUsersResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type Rule struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	RuleId               int64                `protobuf:"varint,2,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	CreatedBy            int64                `protobuf:"varint,3,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	RuleNumber           int64                `protobuf:"varint,4,opt,name=ruleNumber,proto3" json:"ruleNumber,omitempty"`
	Content              string               `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{5}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Rule) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *Rule) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Rule) GetRuleNumber() int64 {
	if m != nil {
		return m.RuleNumber
	}
	return 0
}

func (m *Rule) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CREATE
type CreateRuleRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Rule                 *Rule    `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleRequest) Reset()         { *m = CreateRuleRequest{} }
func (m *CreateRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuleRequest) ProtoMessage()    {}
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{6}
}

func (m *CreateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleRequest.Unmarshal(m, b)
}
func (m *CreateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleRequest.Merge(m, src)
}
func (m *CreateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleRequest.Size(m)
}
func (m *CreateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleRequest proto.InternalMessageInfo

func (m *CreateRuleRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRuleRequest) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type CreateRuleResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleResponse) Reset()         { *m = CreateRuleResponse{} }
func (m *CreateRuleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuleResponse) ProtoMessage()    {}
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{7}
}

func (m *CreateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleResponse.Unmarshal(m, b)
}
func (m *CreateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleResponse.Merge(m, src)
}
func (m *CreateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleResponse.Size(m)
}
func (m *CreateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleResponse proto.InternalMessageInfo

func (m *CreateRuleResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRuleResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindRulesRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	RuleId               int64                `protobuf:"varint,4,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	CreatedBy            int64                `protobuf:"varint,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	RuleNumber           int64                `protobuf:"varint,6,opt,name=ruleNumber,proto3" json:"ruleNumber,omitempty"`
	Content              string               `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int32                `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,10,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindRulesRequest) Reset()         { *m = FindRulesRequest{} }
func (m *FindRulesRequest) String() string { return proto.CompactTextString(m) }
func (*FindRulesRequest) ProtoMessage()    {}
func (*FindRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{8}
}

func (m *FindRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRulesRequest.Unmarshal(m, b)
}
func (m *FindRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRulesRequest.Marshal(b, m, deterministic)
}
func (m *FindRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRulesRequest.Merge(m, src)
}
func (m *FindRulesRequest) XXX_Size() int {
	return xxx_messageInfo_FindRulesRequest.Size(m)
}
func (m *FindRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRulesRequest proto.InternalMessageInfo

func (m *FindRulesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRulesRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindRulesRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindRulesRequest) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *FindRulesRequest) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *FindRulesRequest) GetRuleNumber() int64 {
	if m != nil {
		return m.RuleNumber
	}
	return 0
}

func (m *FindRulesRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindRulesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindRulesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindRulesRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindRulesResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	TotalCount           int64    `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRulesResponse) Reset()         { *m = FindRulesResponse{} }
func (m *FindRulesResponse) String() string { return proto.CompactTextString(m) }
func (*FindRulesResponse) ProtoMessage()    {}
func (*FindRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{9}
}

func (m *FindRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRulesResponse.Unmarshal(m, b)
}
func (m *FindRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRulesResponse.Marshal(b, m, deterministic)
}
func (m *FindRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRulesResponse.Merge(m, src)
}
func (m *FindRulesResponse) XXX_Size() int {
	return xxx_messageInfo_FindRulesResponse.Size(m)
}
func (m *FindRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindRulesResponse proto.InternalMessageInfo

func (m *FindRulesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRulesResponse) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *FindRulesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type Exchange struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	TypeId               int32                `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int32                `protobuf:"varint,3,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,5,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,6,opt,name=registerId,proto3" json:"registerId,omitempty"`
	Content              string               `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{10}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Exchange) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Exchange) GetStateId() int32 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *Exchange) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Exchange) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *Exchange) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *Exchange) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CREATE
type CreateExchangeRequest struct {
	Api                  string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Exchange             *Exchange `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateExchangeRequest) Reset()         { *m = CreateExchangeRequest{} }
func (m *CreateExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeRequest) ProtoMessage()    {}
func (*CreateExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{11}
}

func (m *CreateExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeRequest.Unmarshal(m, b)
}
func (m *CreateExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeRequest.Marshal(b, m, deterministic)
}
func (m *CreateExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeRequest.Merge(m, src)
}
func (m *CreateExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeRequest.Size(m)
}
func (m *CreateExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeRequest proto.InternalMessageInfo

func (m *CreateExchangeRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateExchangeRequest) GetExchange() *Exchange {
	if m != nil {
		return m.Exchange
	}
	return nil
}

type CreateExchangeResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateExchangeResponse) Reset()         { *m = CreateExchangeResponse{} }
func (m *CreateExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeResponse) ProtoMessage()    {}
func (*CreateExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{12}
}

func (m *CreateExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeResponse.Unmarshal(m, b)
}
func (m *CreateExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeResponse.Marshal(b, m, deterministic)
}
func (m *CreateExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeResponse.Merge(m, src)
}
func (m *CreateExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeResponse.Size(m)
}
func (m *CreateExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeResponse proto.InternalMessageInfo

func (m *CreateExchangeResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateExchangeResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindExchangesRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	TypeId               int32                `protobuf:"varint,4,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int32                `protobuf:"varint,5,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,7,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,8,opt,name=registerId,proto3" json:"registerId,omitempty"`
	Content              string               `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int32                `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,12,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindExchangesRequest) Reset()         { *m = FindExchangesRequest{} }
func (m *FindExchangesRequest) String() string { return proto.CompactTextString(m) }
func (*FindExchangesRequest) ProtoMessage()    {}
func (*FindExchangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{13}
}

func (m *FindExchangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindExchangesRequest.Unmarshal(m, b)
}
func (m *FindExchangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindExchangesRequest.Marshal(b, m, deterministic)
}
func (m *FindExchangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindExchangesRequest.Merge(m, src)
}
func (m *FindExchangesRequest) XXX_Size() int {
	return xxx_messageInfo_FindExchangesRequest.Size(m)
}
func (m *FindExchangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindExchangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindExchangesRequest proto.InternalMessageInfo

func (m *FindExchangesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindExchangesRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindExchangesRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindExchangesRequest) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *FindExchangesRequest) GetStateId() int32 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *FindExchangesRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *FindExchangesRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *FindExchangesRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *FindExchangesRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindExchangesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindExchangesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindExchangesRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindExchangesResponse struct {
	Api                  string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Exchanges            []*Exchange `protobuf:"bytes,2,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	TotalCount           int64       `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindExchangesResponse) Reset()         { *m = FindExchangesResponse{} }
func (m *FindExchangesResponse) String() string { return proto.CompactTextString(m) }
func (*FindExchangesResponse) ProtoMessage()    {}
func (*FindExchangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{14}
}

func (m *FindExchangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindExchangesResponse.Unmarshal(m, b)
}
func (m *FindExchangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindExchangesResponse.Marshal(b, m, deterministic)
}
func (m *FindExchangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindExchangesResponse.Merge(m, src)
}
func (m *FindExchangesResponse) XXX_Size() int {
	return xxx_messageInfo_FindExchangesResponse.Size(m)
}
func (m *FindExchangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindExchangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindExchangesResponse proto.InternalMessageInfo

func (m *FindExchangesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindExchangesResponse) GetExchanges() []*Exchange {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

func (m *FindExchangesResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type Declaration struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	DeclarationId        int64                `protobuf:"varint,2,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	UserIp               string               `protobuf:"bytes,5,opt,name=userIp,proto3" json:"userIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Declaration) Reset()         { *m = Declaration{} }
func (m *Declaration) String() string { return proto.CompactTextString(m) }
func (*Declaration) ProtoMessage()    {}
func (*Declaration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{15}
}

func (m *Declaration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Declaration.Unmarshal(m, b)
}
func (m *Declaration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Declaration.Marshal(b, m, deterministic)
}
func (m *Declaration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Declaration.Merge(m, src)
}
func (m *Declaration) XXX_Size() int {
	return xxx_messageInfo_Declaration.Size(m)
}
func (m *Declaration) XXX_DiscardUnknown() {
	xxx_messageInfo_Declaration.DiscardUnknown(m)
}

var xxx_messageInfo_Declaration proto.InternalMessageInfo

func (m *Declaration) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Declaration) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *Declaration) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Declaration) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Declaration) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

// CREATE
type CreateDeclarationRequest struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Declaration          *Declaration `protobuf:"bytes,2,opt,name=declaration,proto3" json:"declaration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateDeclarationRequest) Reset()         { *m = CreateDeclarationRequest{} }
func (m *CreateDeclarationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeclarationRequest) ProtoMessage()    {}
func (*CreateDeclarationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{16}
}

func (m *CreateDeclarationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeclarationRequest.Unmarshal(m, b)
}
func (m *CreateDeclarationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeclarationRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeclarationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeclarationRequest.Merge(m, src)
}
func (m *CreateDeclarationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeclarationRequest.Size(m)
}
func (m *CreateDeclarationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeclarationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeclarationRequest proto.InternalMessageInfo

func (m *CreateDeclarationRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateDeclarationRequest) GetDeclaration() *Declaration {
	if m != nil {
		return m.Declaration
	}
	return nil
}

type CreateDeclarationResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeclarationResponse) Reset()         { *m = CreateDeclarationResponse{} }
func (m *CreateDeclarationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeclarationResponse) ProtoMessage()    {}
func (*CreateDeclarationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{17}
}

func (m *CreateDeclarationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeclarationResponse.Unmarshal(m, b)
}
func (m *CreateDeclarationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeclarationResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeclarationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeclarationResponse.Merge(m, src)
}
func (m *CreateDeclarationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeclarationResponse.Size(m)
}
func (m *CreateDeclarationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeclarationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeclarationResponse proto.InternalMessageInfo

func (m *CreateDeclarationResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateDeclarationResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindDeclarationsRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	DeclarationId        int64                `protobuf:"varint,4,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	UserId               int64                `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	UserIp               string               `protobuf:"bytes,6,opt,name=userIp,proto3" json:"userIp,omitempty"`
	Limit                int32                `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,9,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindDeclarationsRequest) Reset()         { *m = FindDeclarationsRequest{} }
func (m *FindDeclarationsRequest) String() string { return proto.CompactTextString(m) }
func (*FindDeclarationsRequest) ProtoMessage()    {}
func (*FindDeclarationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{18}
}

func (m *FindDeclarationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDeclarationsRequest.Unmarshal(m, b)
}
func (m *FindDeclarationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDeclarationsRequest.Marshal(b, m, deterministic)
}
func (m *FindDeclarationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDeclarationsRequest.Merge(m, src)
}
func (m *FindDeclarationsRequest) XXX_Size() int {
	return xxx_messageInfo_FindDeclarationsRequest.Size(m)
}
func (m *FindDeclarationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDeclarationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindDeclarationsRequest proto.InternalMessageInfo

func (m *FindDeclarationsRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindDeclarationsRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindDeclarationsRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindDeclarationsRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *FindDeclarationsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FindDeclarationsRequest) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

func (m *FindDeclarationsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindDeclarationsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindDeclarationsRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindDeclarationsResponse struct {
	Api                  string         `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Declarations         []*Declaration `protobuf:"bytes,2,rep,name=declarations,proto3" json:"declarations,omitempty"`
	TotalCount           int64          `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindDeclarationsResponse) Reset()         { *m = FindDeclarationsResponse{} }
func (m *FindDeclarationsResponse) String() string { return proto.CompactTextString(m) }
func (*FindDeclarationsResponse) ProtoMessage()    {}
func (*FindDeclarationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{19}
}

func (m *FindDeclarationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDeclarationsResponse.Unmarshal(m, b)
}
func (m *FindDeclarationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDeclarationsResponse.Marshal(b, m, deterministic)
}
func (m *FindDeclarationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDeclarationsResponse.Merge(m, src)
}
func (m *FindDeclarationsResponse) XXX_Size() int {
	return xxx_messageInfo_FindDeclarationsResponse.Size(m)
}
func (m *FindDeclarationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDeclarationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindDeclarationsResponse proto.InternalMessageInfo

func (m *FindDeclarationsResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindDeclarationsResponse) GetDeclarations() []*Declaration {
	if m != nil {
		return m.Declarations
	}
	return nil
}

func (m *FindDeclarationsResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "v2.User")
	proto.RegisterType((*CreateUserRequest)(nil), "v2.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "v2.CreateUserResponse")
	proto.RegisterType((*FindUsersRequest)(nil), "v2.FindUsersRequest")
	proto.RegisterType((*FindUsersResponse)(nil), "v2.FindUsersResponse")
	proto.RegisterType((*Rule)(nil), "v2.Rule")
	proto.RegisterType((*CreateRuleRequest)(nil), "v2.CreateRuleRequest")
	proto.RegisterType((*CreateRuleResponse)(nil), "v2.CreateRuleResponse")
	proto.RegisterType((*FindRulesRequest)(nil), "v2.FindRulesRequest")
	proto.RegisterType((*FindRulesResponse)(nil), "v2.FindRulesResponse")
	proto.RegisterType((*Exchange)(nil), "v2.Exchange")
	proto.RegisterType((*CreateExchangeRequest)(nil), "v2.CreateExchangeRequest")
	proto.RegisterType((*CreateExchangeResponse)(nil), "v2.CreateExchangeResponse")
	proto.RegisterType((*FindExchangesRequest)(nil), "v2.FindExchangesRequest")
	proto.RegisterType((*FindExchangesResponse)(nil), "v2.FindExchangesResponse")
	proto.RegisterType((*Declaration)(nil), "v2.Declaration")
	proto.RegisterType((*CreateDeclarationRequest)(nil), "v2.CreateDeclarationRequest")
	proto.RegisterType((*CreateDeclarationResponse)(nil), "v2.CreateDeclarationResponse")
	proto.RegisterType((*FindDeclarationsRequest)(nil), "v2.FindDeclarationsRequest")
	proto.RegisterType((*FindDeclarationsResponse)(nil), "v2.FindDeclarationsResponse")
}

func init() { proto.RegisterFile("logging-service.proto", fileDescriptor_1fb7a78083aef92b) }

var fileDescriptor_1fb7a78083aef92b = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0x13, 0x3b, 0x89, 0x4f, 0x12, 0xda, 0x8e, 0x36, 0xc1, 0x6b, 0x42, 0x59, 0x59, 0x48,
	0x44, 0x48, 0xa4, 0x22, 0xbd, 0xa9, 0x04, 0x42, 0x90, 0x6d, 0x8b, 0x2a, 0x01, 0x42, 0x6e, 0xb9,
	0x5b, 0x09, 0x79, 0x93, 0x59, 0x63, 0xe1, 0xd8, 0xc1, 0x1e, 0x47, 0x2c, 0x77, 0x48, 0x5c, 0xf1,
	0x14, 0x7d, 0x01, 0x24, 0xae, 0xe0, 0x19, 0xe0, 0x19, 0xb8, 0xe2, 0x19, 0x78, 0x00, 0x34, 0x3f,
	0xb6, 0xc7, 0x89, 0xc7, 0xd1, 0x6a, 0x2b, 0x35, 0x77, 0x99, 0xe3, 0x99, 0xe3, 0x2f, 0xdf, 0xf7,
	0x9d, 0x33, 0xc7, 0x30, 0x0a, 0x63, 0xdf, 0x0f, 0x22, 0xff, 0x83, 0x14, 0x27, 0xdb, 0x60, 0x89,
	0x67, 0x9b, 0x24, 0x26, 0x31, 0x6a, 0x6d, 0xe7, 0xf6, 0x3b, 0x7e, 0x1c, 0xfb, 0x21, 0x7e, 0xc0,
	0x22, 0x97, 0xd9, 0xd5, 0x03, 0x12, 0xac, 0x71, 0x4a, 0xbc, 0xf5, 0x86, 0x6f, 0x72, 0x7e, 0xd5,
	0x40, 0xff, 0x26, 0xc5, 0x09, 0x7a, 0x04, 0xe6, 0x32, 0xc1, 0x1e, 0xc1, 0xab, 0xcf, 0x88, 0xa5,
	0x9d, 0x69, 0xd3, 0xfe, 0xdc, 0x9e, 0xf1, 0xd3, 0xb3, 0xfc, 0xf4, 0xec, 0x45, 0x7e, 0xda, 0x2d,
	0x37, 0xa3, 0x31, 0x74, 0xb2, 0x14, 0x27, 0xcf, 0x56, 0x56, 0xeb, 0x4c, 0x9b, 0xb6, 0x5d, 0xb1,
	0xa2, 0x71, 0x72, 0xbd, 0xc1, 0xcf, 0x56, 0x56, 0x9b, 0xc7, 0xf9, 0x0a, 0x59, 0xd0, 0x5d, 0xc6,
	0x11, 0xc1, 0x11, 0xb1, 0xf4, 0x33, 0x6d, 0x6a, 0xba, 0xf9, 0xd2, 0x39, 0x87, 0x7b, 0xe7, 0x2c,
	0x2d, 0x45, 0xe4, 0xe2, 0x1f, 0x32, 0x9c, 0x12, 0x74, 0x17, 0xda, 0xde, 0x26, 0x60, 0x90, 0x4c,
	0x97, 0xfe, 0x44, 0x13, 0xd0, 0xe9, 0x2b, 0xd8, 0xeb, 0xfa, 0xf3, 0xde, 0x6c, 0x3b, 0x9f, 0xb1,
	0x03, 0x2c, 0xea, 0x7c, 0x02, 0x48, 0x4e, 0x92, 0x6e, 0xe2, 0x28, 0xc5, 0x35, 0x59, 0xc6, 0xd0,
	0x49, 0x89, 0x47, 0xb2, 0x94, 0xe5, 0x31, 0x5c, 0xb1, 0x72, 0xfe, 0x68, 0xc1, 0xdd, 0xa7, 0x41,
	0xb4, 0xa2, 0xc7, 0x53, 0x35, 0x88, 0x4f, 0x61, 0x58, 0x50, 0xf0, 0x34, 0x89, 0xd7, 0x02, 0x4d,
	0x13, 0x67, 0xd5, 0x03, 0xe8, 0x63, 0xe8, 0x17, 0x81, 0x17, 0x31, 0x23, 0xa9, 0xf9, 0xbc, 0xbc,
	0x5d, 0x62, 0x5d, 0x57, 0xb0, 0x6e, 0xa8, 0x58, 0xef, 0x54, 0x58, 0x47, 0x27, 0x60, 0x84, 0xc1,
	0x3a, 0x20, 0x56, 0x97, 0xf1, 0xc0, 0x17, 0x34, 0x4f, 0x7c, 0x75, 0x95, 0x62, 0x62, 0xf5, 0x38,
	0x3d, 0x7c, 0x45, 0xf3, 0xc4, 0xc9, 0x0a, 0x27, 0x8b, 0x6b, 0xcb, 0xe4, 0x79, 0xc4, 0xd2, 0xc1,
	0x70, 0x4f, 0xe2, 0x4d, 0xc9, 0xfb, 0x7d, 0x30, 0x28, 0x54, 0x4a, 0x7b, 0xbb, 0x22, 0x1f, 0x0f,
	0xa3, 0xfb, 0x00, 0x24, 0x26, 0x5e, 0x78, 0x1e, 0x67, 0x11, 0x11, 0xd6, 0x91, 0x22, 0xce, 0xef,
	0x1a, 0xe8, 0x6e, 0x16, 0xe2, 0xdb, 0x39, 0x36, 0xc9, 0x42, 0x5c, 0x3a, 0x96, 0xaf, 0xd0, 0xa4,
	0xc8, 0xb8, 0xb8, 0x16, 0x6f, 0x2e, 0x03, 0x14, 0x18, 0xdd, 0xf7, 0x55, 0xb6, 0xbe, 0xc4, 0x89,
	0x60, 0x5d, 0x8a, 0xc8, 0x0c, 0x1b, 0x0a, 0x5f, 0x53, 0xdc, 0x8d, 0xbe, 0xa6, 0xe9, 0x64, 0x5f,
	0xb3, 0x03, 0x2c, 0x5a, 0xfa, 0x9a, 0x27, 0xb9, 0xb1, 0xaf, 0xff, 0x11, 0xbe, 0xa6, 0xc7, 0x8f,
	0xdb, 0xd7, 0x42, 0x1b, 0x5d, 0xad, 0x8d, 0xd1, 0xac, 0x4d, 0xa7, 0x49, 0x9b, 0xae, 0xc2, 0xfd,
	0xbd, 0x7a, 0xf7, 0x9b, 0x2a, 0xf7, 0x43, 0xad, 0xfb, 0x05, 0xbb, 0x4d, 0xee, 0xa7, 0xb0, 0x2a,
	0xee, 0x67, 0x82, 0xf2, 0xf0, 0x41, 0xf7, 0xff, 0xa7, 0x41, 0xef, 0xc9, 0x8f, 0xcb, 0xef, 0xbc,
	0xc8, 0xbf, 0x65, 0x05, 0x88, 0x2e, 0x21, 0x4c, 0x52, 0x76, 0x09, 0x6a, 0x97, 0xbc, 0x69, 0x1b,
	0x6e, 0xbe, 0xa4, 0xfc, 0x27, 0xdc, 0x34, 0x85, 0x34, 0x65, 0x00, 0xbd, 0x0b, 0xc3, 0x15, 0x5e,
	0x86, 0x5e, 0xe2, 0x91, 0x20, 0x8e, 0x8a, 0xe6, 0x53, 0x0d, 0x32, 0x95, 0xb0, 0x1f, 0xa4, 0x84,
	0xf5, 0x2d, 0xde, 0x86, 0xa4, 0x88, 0x5a, 0x25, 0xe7, 0x39, 0x8c, 0xb8, 0xf9, 0xf3, 0xff, 0xae,
	0x36, 0xf0, 0x14, 0x7a, 0x58, 0x6c, 0x12, 0xde, 0x1d, 0x50, 0x92, 0x8b, 0x83, 0xc5, 0x53, 0x67,
	0x01, 0xe3, 0xdd, 0xa4, 0x37, 0xae, 0xaa, 0x97, 0x6d, 0x38, 0xa1, 0xba, 0xe7, 0x29, 0x8e, 0xbb,
	0xb2, 0x84, 0xe6, 0xba, 0x4a, 0x73, 0xa3, 0x41, 0xf3, 0xce, 0x41, 0xcd, 0xbb, 0x87, 0x35, 0xef,
	0x35, 0x69, 0x6e, 0x2a, 0x2a, 0x13, 0xea, 0x2b, 0xb3, 0xaf, 0xaa, 0xcc, 0x41, 0xb5, 0x32, 0x33,
	0x18, 0xed, 0x28, 0xa4, 0x54, 0xf9, 0x7d, 0x30, 0x73, 0x77, 0xe4, 0x15, 0x5a, 0x35, 0x4f, 0xf9,
	0xf8, 0x60, 0xa5, 0xfe, 0xa9, 0x41, 0xff, 0x71, 0x49, 0xc5, 0x2d, 0x8a, 0x75, 0x8f, 0xe8, 0x56,
	0x1d, 0xd1, 0x12, 0x91, 0xed, 0x2a, 0x91, 0x0d, 0xa3, 0x02, 0xfb, 0xb5, 0x11, 0xf7, 0x95, 0x58,
	0x39, 0xdf, 0x82, 0xc5, 0xeb, 0x42, 0x82, 0xaf, 0xb6, 0xf5, 0x87, 0xd0, 0x97, 0x80, 0x08, 0x53,
	0xdf, 0xa1, 0xac, 0xc9, 0xc7, 0xe5, 0x3d, 0xce, 0x13, 0x38, 0xad, 0x79, 0xc1, 0x8d, 0x6b, 0xef,
	0xaf, 0x16, 0xbc, 0x49, 0x95, 0x95, 0xb2, 0x1c, 0x71, 0xf9, 0xed, 0xa9, 0xa8, 0xd7, 0xa9, 0x58,
	0x6a, 0x65, 0x28, 0xb4, 0xea, 0xc8, 0x5a, 0xbd, 0xb2, 0xe1, 0xed, 0x67, 0x0d, 0xac, 0x7d, 0x2e,
	0x95, 0x92, 0x3c, 0x84, 0x81, 0x84, 0x3b, 0xaf, 0x95, 0x3d, 0xd5, 0x2b, 0x9b, 0x0e, 0x55, 0xcc,
	0xfc, 0x17, 0x0d, 0xfa, 0x74, 0x12, 0x7c, 0xce, 0x3f, 0x63, 0xd0, 0x47, 0x00, 0xe5, 0x24, 0x8f,
	0x46, 0x34, 0xf9, 0xde, 0xe7, 0x81, 0x3d, 0xde, 0x0d, 0x0b, 0xcc, 0x8f, 0xc0, 0x2c, 0xa6, 0x51,
	0x74, 0x42, 0x37, 0xed, 0x0e, 0xf5, 0xf6, 0x68, 0x27, 0xca, 0x4f, 0x32, 0x18, 0xf4, 0x4a, 0xde,
	0x83, 0xc1, 0xa6, 0x4e, 0x09, 0x86, 0x34, 0xcd, 0xc9, 0x30, 0x2a, 0xf3, 0x99, 0x80, 0xc1, 0xc6,
	0x82, 0x12, 0x86, 0x3c, 0x83, 0x95, 0x30, 0x2a, 0xb3, 0xc3, 0xfc, 0xa5, 0x06, 0x77, 0xf2, 0xbe,
	0x93, 0x43, 0xf9, 0x1c, 0xde, 0xa8, 0xde, 0x58, 0xe8, 0xb4, 0x7c, 0xef, 0xce, 0xd5, 0x68, 0xdb,
	0x75, 0x8f, 0x04, 0xac, 0xc7, 0x30, 0xac, 0xf4, 0x44, 0x64, 0xe5, 0x20, 0x76, 0x2f, 0x32, 0xfb,
	0xb4, 0xe6, 0x89, 0x80, 0xf8, 0x9b, 0x0e, 0xc3, 0x2f, 0xd8, 0xb7, 0xe7, 0xeb, 0x95, 0xec, 0x35,
	0x49, 0x74, 0x64, 0x72, 0xa0, 0xaf, 0xf3, 0xcf, 0x0c, 0xf9, 0xda, 0x99, 0x94, 0xaf, 0xdd, 0x6f,
	0xe7, 0xf6, 0xdb, 0x8a, 0xa7, 0x22, 0xe3, 0x97, 0xfc, 0x93, 0x41, 0x6e, 0x0a, 0xe8, 0xad, 0x1c,
	0x40, 0x4d, 0xdb, 0xb5, 0x27, 0xf5, 0x0f, 0x79, 0xba, 0xc5, 0x7b, 0x7f, 0xb7, 0x06, 0x91, 0xf7,
	0xd3, 0xf7, 0x17, 0x61, 0xec, 0xa7, 0x17, 0xdb, 0xf9, 0xbf, 0xad, 0x91, 0xbc, 0xbc, 0x58, 0x63,
	0xe2, 0xad, 0x3c, 0xe2, 0x5d, 0x76, 0x58, 0x33, 0x7d, 0xf8, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0x49, 0x9f, 0x03, 0xda, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/v2.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error) {
	out := new(FindUsersResponse)
	err := c.cc.Invoke(ctx, "/v2.UserService/FindUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUsers(context.Context, *FindUsersRequest) (*FindUsersResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.UserService/FindUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindUsers(ctx, req.(*FindUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "FindUsers",
			Handler:    _UserService_FindUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// RuleServiceClient is the client API for RuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuleServiceClient interface {
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error)
	FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error)
}

type ruleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuleServiceClient(cc *grpc.ClientConn) RuleServiceClient {
	return &ruleServiceClient{cc}
}

func (c *ruleServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error) {
	out := new(CreateRuleResponse)
	err := c.cc.Invoke(ctx, "/v2.RuleService/CreateRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error) {
	out := new(FindRulesResponse)
	err := c.cc.Invoke(ctx, "/v2.RuleService/FindRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServiceServer is the server API for RuleService service.
type RuleServiceServer interface {
	CreateRule(context.Context, *CreateRuleRequest) (*CreateRuleResponse, error)
	FindRules(context.Context, *FindRulesRequest) (*FindRulesResponse, error)
}

func RegisterRuleServiceServer(s *grpc.Server, srv RuleServiceServer) {
	s.RegisterService(&_RuleService_serviceDesc, srv)
}

func _RuleService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.RuleService/CreateRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_FindRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).FindRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.RuleService/FindRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).FindRules(ctx, req.(*FindRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.RuleService",
	HandlerType: (*RuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRule",
			Handler:    _RuleService_CreateRule_Handler,
		},
		{
			MethodName: "FindRules",
			Handler:    _RuleService_FindRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// ExchangeServiceClient is the client API for ExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeServiceClient interface {
	CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error)
	FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error)
}

type exchangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewExchangeServiceClient(cc *grpc.ClientConn) ExchangeServiceClient {
	return &exchangeServiceClient{cc}
}

func (c *exchangeServiceClient) CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error) {
	out := new(CreateExchangeResponse)
	err := c.cc.Invoke(ctx, "/v2.ExchangeService/CreateExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error) {
	out := new(FindExchangesResponse)
	err := c.cc.Invoke(ctx, "/v2.ExchangeService/FindExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeServiceServer is the server API for ExchangeService service.
type ExchangeServiceServer interface {
	CreateExchange(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error)
	FindExchanges(context.Context, *FindExchangesRequest) (*FindExchangesResponse, error)
}

func RegisterExchangeServiceServer(s *grpc.Server, srv ExchangeServiceServer) {
	s.RegisterService(&_ExchangeService_serviceDesc, srv)
}

func _ExchangeService_CreateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).CreateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.ExchangeService/CreateExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).CreateExchange(ctx, req.(*CreateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_FindExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).FindExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.ExchangeService/FindExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).FindExchanges(ctx, req.(*FindExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExchangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.ExchangeService",
	HandlerType: (*ExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExchange",
			Handler:    _ExchangeService_CreateExchange_Handler,
		},
		{
			MethodName: "FindExchanges",
			Handler:    _ExchangeService_FindExchanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// LogginServiceClient is the client API for LogginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogginServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error)
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error)
	FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error)
	CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error)
	FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error)
	CreateDeclaration(ctx context.Context, in *CreateDeclarationRequest, opts ...grpc.CallOption) (*CreateDeclarationResponse, error)
	FindDeclarations(ctx context.Context, in *FindDeclarationsRequest, opts ...grpc.CallOption) (*FindDeclarationsResponse, error)
}

type logginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogginServiceClient(cc *grpc.ClientConn) LogginServiceClient {
	return &logginServiceClient{cc}
}

func (c *logginServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error) {
	out := new(FindUsersResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error) {
	out := new(CreateRuleResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error) {
	out := new(FindRulesResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error) {
	out := new(CreateExchangeResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error) {
	out := new(FindExchangesResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) CreateDeclaration(ctx context.Context, in *CreateDeclarationRequest, opts ...grpc.CallOption) (*CreateDeclarationResponse, error) {
	out := new(CreateDeclarationResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateDeclaration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindDeclarations(ctx context.Context, in *FindDeclarationsRequest, opts ...grpc.CallOption) (*FindDeclarationsResponse, error) {
	out := new(FindDeclarationsResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindDeclarations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogginServiceServer is the server API for LogginService service.
type LogginServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUsers(context.Context, *FindUsersRequest) (*FindUsersResponse, error)
	CreateRule(context.Context, *CreateRuleRequest) (*CreateRuleResponse, error)
	FindRules(context.Context, *FindRulesRequest) (*FindRulesResponse, error)
	CreateExchange(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error)
	FindExchanges(context.Context, *FindExchangesRequest) (*FindExchangesResponse, error)
	CreateDeclaration(context.Context, *CreateDeclarationRequest) (*CreateDeclarationResponse, error)
	FindDeclarations(context.Context, *FindDeclarationsRequest) (*FindDeclarationsResponse, error)
}

func RegisterLogginServiceServer(s *grpc.Server, srv LogginServiceServer) {
	s.RegisterService(&_LogginService_serviceDesc, srv)
}

func _LogginService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindUsers(ctx, req.(*FindUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindRules(ctx, req.(*FindRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_CreateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateExchange(ctx, req.(*CreateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindExchanges(ctx, req.(*FindExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_CreateDeclaration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeclarationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateDeclaration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateDeclaration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateDeclaration(ctx, req.(*CreateDeclarationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindDeclarations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDeclarationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindDeclarations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindDeclarations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindDeclarations(ctx, req.(*FindDeclarationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.LogginService",
	HandlerType: (*LogginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _LogginService_CreateUser_Handler,
		},
		{
			MethodName: "FindUsers",
			Handler:    _LogginService_FindUsers_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _LogginService_CreateRule_Handler,
		},
		{
			MethodName: "FindRules",
			Handler:    _LogginService_FindRules_Handler,
		},
		{
			MethodName: "CreateExchange",
			Handler:    _LogginService_CreateExchange_Handler,
		},
		{
			MethodName: "FindExchanges",
			Handler:    _LogginService_FindExchanges_Handler,
		},
		{
			MethodName: "CreateDeclaration",
			Handler:    _LogginService_CreateDeclaration_Handler,
		},
		{
			MethodName: "FindDeclarations",
			Handler:    _LogginService_FindDeclarations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}
