// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logging-service.proto

package v2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId               int64                `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 string               `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Content              string               `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *User) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CREATE
type CreateUserRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindUsersRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Content              string               `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int32                `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,9,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindUsersRequest) Reset()         { *m = FindUsersRequest{} }
func (m *FindUsersRequest) String() string { return proto.CompactTextString(m) }
func (*FindUsersRequest) ProtoMessage()    {}
func (*FindUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{3}
}

func (m *FindUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUsersRequest.Unmarshal(m, b)
}
func (m *FindUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUsersRequest.Marshal(b, m, deterministic)
}
func (m *FindUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUsersRequest.Merge(m, src)
}
func (m *FindUsersRequest) XXX_Size() int {
	return xxx_messageInfo_FindUsersRequest.Size(m)
}
func (m *FindUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUsersRequest proto.InternalMessageInfo

func (m *FindUsersRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUsersRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindUsersRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindUsersRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FindUsersRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FindUsersRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindUsersRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindUsersResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUsersResponse) Reset()         { *m = FindUsersResponse{} }
func (m *FindUsersResponse) String() string { return proto.CompactTextString(m) }
func (*FindUsersResponse) ProtoMessage()    {}
func (*FindUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{4}
}

func (m *FindUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUsersResponse.Unmarshal(m, b)
}
func (m *FindUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUsersResponse.Marshal(b, m, deterministic)
}
func (m *FindUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUsersResponse.Merge(m, src)
}
func (m *FindUsersResponse) XXX_Size() int {
	return xxx_messageInfo_FindUsersResponse.Size(m)
}
func (m *FindUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUsersResponse proto.InternalMessageInfo

func (m *FindUsersResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// DELETE
type DeleteUsersRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteUsersRequest) Reset()         { *m = DeleteUsersRequest{} }
func (m *DeleteUsersRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUsersRequest) ProtoMessage()    {}
func (*DeleteUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{5}
}

func (m *DeleteUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUsersRequest.Unmarshal(m, b)
}
func (m *DeleteUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUsersRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUsersRequest.Merge(m, src)
}
func (m *DeleteUsersRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUsersRequest.Size(m)
}
func (m *DeleteUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUsersRequest proto.InternalMessageInfo

func (m *DeleteUsersRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteUsersRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *DeleteUsersRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *DeleteUsersRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteUsersRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type DeleteUsersResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUsersResponse) Reset()         { *m = DeleteUsersResponse{} }
func (m *DeleteUsersResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUsersResponse) ProtoMessage()    {}
func (*DeleteUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{6}
}

func (m *DeleteUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUsersResponse.Unmarshal(m, b)
}
func (m *DeleteUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUsersResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUsersResponse.Merge(m, src)
}
func (m *DeleteUsersResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUsersResponse.Size(m)
}
func (m *DeleteUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUsersResponse proto.InternalMessageInfo

func (m *DeleteUsersResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteUsersResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Rule struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	RuleId               int64                `protobuf:"varint,2,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	CreatedBy            int64                `protobuf:"varint,3,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	RuleNumber           int64                `protobuf:"varint,4,opt,name=ruleNumber,proto3" json:"ruleNumber,omitempty"`
	Content              string               `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{7}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Rule) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *Rule) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Rule) GetRuleNumber() int64 {
	if m != nil {
		return m.RuleNumber
	}
	return 0
}

func (m *Rule) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CREATE
type CreateRuleRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Rule                 *Rule    `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleRequest) Reset()         { *m = CreateRuleRequest{} }
func (m *CreateRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuleRequest) ProtoMessage()    {}
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{8}
}

func (m *CreateRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleRequest.Unmarshal(m, b)
}
func (m *CreateRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleRequest.Merge(m, src)
}
func (m *CreateRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleRequest.Size(m)
}
func (m *CreateRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleRequest proto.InternalMessageInfo

func (m *CreateRuleRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRuleRequest) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type CreateRuleResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleResponse) Reset()         { *m = CreateRuleResponse{} }
func (m *CreateRuleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuleResponse) ProtoMessage()    {}
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{9}
}

func (m *CreateRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleResponse.Unmarshal(m, b)
}
func (m *CreateRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleResponse.Marshal(b, m, deterministic)
}
func (m *CreateRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleResponse.Merge(m, src)
}
func (m *CreateRuleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleResponse.Size(m)
}
func (m *CreateRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleResponse proto.InternalMessageInfo

func (m *CreateRuleResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRuleResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindRulesRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	RuleId               int64                `protobuf:"varint,4,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	CreatedBy            int64                `protobuf:"varint,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	RuleNumber           int64                `protobuf:"varint,6,opt,name=ruleNumber,proto3" json:"ruleNumber,omitempty"`
	Content              string               `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int32                `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,10,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindRulesRequest) Reset()         { *m = FindRulesRequest{} }
func (m *FindRulesRequest) String() string { return proto.CompactTextString(m) }
func (*FindRulesRequest) ProtoMessage()    {}
func (*FindRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{10}
}

func (m *FindRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRulesRequest.Unmarshal(m, b)
}
func (m *FindRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRulesRequest.Marshal(b, m, deterministic)
}
func (m *FindRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRulesRequest.Merge(m, src)
}
func (m *FindRulesRequest) XXX_Size() int {
	return xxx_messageInfo_FindRulesRequest.Size(m)
}
func (m *FindRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRulesRequest proto.InternalMessageInfo

func (m *FindRulesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRulesRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindRulesRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindRulesRequest) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *FindRulesRequest) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *FindRulesRequest) GetRuleNumber() int64 {
	if m != nil {
		return m.RuleNumber
	}
	return 0
}

func (m *FindRulesRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindRulesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindRulesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindRulesRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindRulesResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRulesResponse) Reset()         { *m = FindRulesResponse{} }
func (m *FindRulesResponse) String() string { return proto.CompactTextString(m) }
func (*FindRulesResponse) ProtoMessage()    {}
func (*FindRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{11}
}

func (m *FindRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRulesResponse.Unmarshal(m, b)
}
func (m *FindRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRulesResponse.Marshal(b, m, deterministic)
}
func (m *FindRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRulesResponse.Merge(m, src)
}
func (m *FindRulesResponse) XXX_Size() int {
	return xxx_messageInfo_FindRulesResponse.Size(m)
}
func (m *FindRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindRulesResponse proto.InternalMessageInfo

func (m *FindRulesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindRulesResponse) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// DELETE
type DeleteRulesRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	RuleId               int64                `protobuf:"varint,4,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	CreatedBy            int64                `protobuf:"varint,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	RuleNumber           int64                `protobuf:"varint,6,opt,name=ruleNumber,proto3" json:"ruleNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteRulesRequest) Reset()         { *m = DeleteRulesRequest{} }
func (m *DeleteRulesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRulesRequest) ProtoMessage()    {}
func (*DeleteRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{12}
}

func (m *DeleteRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRulesRequest.Unmarshal(m, b)
}
func (m *DeleteRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRulesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRulesRequest.Merge(m, src)
}
func (m *DeleteRulesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRulesRequest.Size(m)
}
func (m *DeleteRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRulesRequest proto.InternalMessageInfo

func (m *DeleteRulesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRulesRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *DeleteRulesRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *DeleteRulesRequest) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *DeleteRulesRequest) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *DeleteRulesRequest) GetRuleNumber() int64 {
	if m != nil {
		return m.RuleNumber
	}
	return 0
}

type DeleteRulesResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRulesResponse) Reset()         { *m = DeleteRulesResponse{} }
func (m *DeleteRulesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRulesResponse) ProtoMessage()    {}
func (*DeleteRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{13}
}

func (m *DeleteRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRulesResponse.Unmarshal(m, b)
}
func (m *DeleteRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRulesResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRulesResponse.Merge(m, src)
}
func (m *DeleteRulesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRulesResponse.Size(m)
}
func (m *DeleteRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRulesResponse proto.InternalMessageInfo

func (m *DeleteRulesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRulesResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Exchange struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	TypeId               int32                `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int32                `protobuf:"varint,3,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,5,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,6,opt,name=registerId,proto3" json:"registerId,omitempty"`
	Content              string               `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{14}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Exchange) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Exchange) GetStateId() int32 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *Exchange) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Exchange) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *Exchange) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *Exchange) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CREATE
type CreateExchangeRequest struct {
	Api                  string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Exchange             *Exchange `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateExchangeRequest) Reset()         { *m = CreateExchangeRequest{} }
func (m *CreateExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeRequest) ProtoMessage()    {}
func (*CreateExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{15}
}

func (m *CreateExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeRequest.Unmarshal(m, b)
}
func (m *CreateExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeRequest.Marshal(b, m, deterministic)
}
func (m *CreateExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeRequest.Merge(m, src)
}
func (m *CreateExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeRequest.Size(m)
}
func (m *CreateExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeRequest proto.InternalMessageInfo

func (m *CreateExchangeRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateExchangeRequest) GetExchange() *Exchange {
	if m != nil {
		return m.Exchange
	}
	return nil
}

type CreateExchangeResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateExchangeResponse) Reset()         { *m = CreateExchangeResponse{} }
func (m *CreateExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeResponse) ProtoMessage()    {}
func (*CreateExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{16}
}

func (m *CreateExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeResponse.Unmarshal(m, b)
}
func (m *CreateExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeResponse.Marshal(b, m, deterministic)
}
func (m *CreateExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeResponse.Merge(m, src)
}
func (m *CreateExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeResponse.Size(m)
}
func (m *CreateExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeResponse proto.InternalMessageInfo

func (m *CreateExchangeResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateExchangeResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// FIND
type FindExchangesRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	TypeId               int32                `protobuf:"varint,4,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int32                `protobuf:"varint,5,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,7,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,8,opt,name=registerId,proto3" json:"registerId,omitempty"`
	Content              string               `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int32                `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,12,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindExchangesRequest) Reset()         { *m = FindExchangesRequest{} }
func (m *FindExchangesRequest) String() string { return proto.CompactTextString(m) }
func (*FindExchangesRequest) ProtoMessage()    {}
func (*FindExchangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{17}
}

func (m *FindExchangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindExchangesRequest.Unmarshal(m, b)
}
func (m *FindExchangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindExchangesRequest.Marshal(b, m, deterministic)
}
func (m *FindExchangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindExchangesRequest.Merge(m, src)
}
func (m *FindExchangesRequest) XXX_Size() int {
	return xxx_messageInfo_FindExchangesRequest.Size(m)
}
func (m *FindExchangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindExchangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindExchangesRequest proto.InternalMessageInfo

func (m *FindExchangesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindExchangesRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *FindExchangesRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *FindExchangesRequest) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *FindExchangesRequest) GetStateId() int32 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *FindExchangesRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *FindExchangesRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *FindExchangesRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *FindExchangesRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindExchangesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindExchangesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindExchangesRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindExchangesResponse struct {
	Api                  string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Exchanges            []*Exchange `protobuf:"bytes,2,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindExchangesResponse) Reset()         { *m = FindExchangesResponse{} }
func (m *FindExchangesResponse) String() string { return proto.CompactTextString(m) }
func (*FindExchangesResponse) ProtoMessage()    {}
func (*FindExchangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{18}
}

func (m *FindExchangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindExchangesResponse.Unmarshal(m, b)
}
func (m *FindExchangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindExchangesResponse.Marshal(b, m, deterministic)
}
func (m *FindExchangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindExchangesResponse.Merge(m, src)
}
func (m *FindExchangesResponse) XXX_Size() int {
	return xxx_messageInfo_FindExchangesResponse.Size(m)
}
func (m *FindExchangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindExchangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindExchangesResponse proto.InternalMessageInfo

func (m *FindExchangesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindExchangesResponse) GetExchanges() []*Exchange {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

// DELETE
type DeleteExchangesRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	CreatedAtFrom        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAtFrom,proto3" json:"createdAtFrom,omitempty"`
	CreatedAtTo          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAtTo,proto3" json:"createdAtTo,omitempty"`
	TypeId               int32                `protobuf:"varint,4,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int32                `protobuf:"varint,5,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,7,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,8,opt,name=registerId,proto3" json:"registerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteExchangesRequest) Reset()         { *m = DeleteExchangesRequest{} }
func (m *DeleteExchangesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteExchangesRequest) ProtoMessage()    {}
func (*DeleteExchangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{19}
}

func (m *DeleteExchangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteExchangesRequest.Unmarshal(m, b)
}
func (m *DeleteExchangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteExchangesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteExchangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteExchangesRequest.Merge(m, src)
}
func (m *DeleteExchangesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteExchangesRequest.Size(m)
}
func (m *DeleteExchangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteExchangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteExchangesRequest proto.InternalMessageInfo

func (m *DeleteExchangesRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteExchangesRequest) GetCreatedAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtFrom
	}
	return nil
}

func (m *DeleteExchangesRequest) GetCreatedAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtTo
	}
	return nil
}

func (m *DeleteExchangesRequest) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *DeleteExchangesRequest) GetStateId() int32 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *DeleteExchangesRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *DeleteExchangesRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *DeleteExchangesRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

type DeleteExchangesResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteExchangesResponse) Reset()         { *m = DeleteExchangesResponse{} }
func (m *DeleteExchangesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteExchangesResponse) ProtoMessage()    {}
func (*DeleteExchangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{20}
}

func (m *DeleteExchangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteExchangesResponse.Unmarshal(m, b)
}
func (m *DeleteExchangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteExchangesResponse.Marshal(b, m, deterministic)
}
func (m *DeleteExchangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteExchangesResponse.Merge(m, src)
}
func (m *DeleteExchangesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteExchangesResponse.Size(m)
}
func (m *DeleteExchangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteExchangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteExchangesResponse proto.InternalMessageInfo

func (m *DeleteExchangesResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteExchangesResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "v2.User")
	proto.RegisterType((*CreateUserRequest)(nil), "v2.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "v2.CreateUserResponse")
	proto.RegisterType((*FindUsersRequest)(nil), "v2.FindUsersRequest")
	proto.RegisterType((*FindUsersResponse)(nil), "v2.FindUsersResponse")
	proto.RegisterType((*DeleteUsersRequest)(nil), "v2.DeleteUsersRequest")
	proto.RegisterType((*DeleteUsersResponse)(nil), "v2.DeleteUsersResponse")
	proto.RegisterType((*Rule)(nil), "v2.Rule")
	proto.RegisterType((*CreateRuleRequest)(nil), "v2.CreateRuleRequest")
	proto.RegisterType((*CreateRuleResponse)(nil), "v2.CreateRuleResponse")
	proto.RegisterType((*FindRulesRequest)(nil), "v2.FindRulesRequest")
	proto.RegisterType((*FindRulesResponse)(nil), "v2.FindRulesResponse")
	proto.RegisterType((*DeleteRulesRequest)(nil), "v2.DeleteRulesRequest")
	proto.RegisterType((*DeleteRulesResponse)(nil), "v2.DeleteRulesResponse")
	proto.RegisterType((*Exchange)(nil), "v2.Exchange")
	proto.RegisterType((*CreateExchangeRequest)(nil), "v2.CreateExchangeRequest")
	proto.RegisterType((*CreateExchangeResponse)(nil), "v2.CreateExchangeResponse")
	proto.RegisterType((*FindExchangesRequest)(nil), "v2.FindExchangesRequest")
	proto.RegisterType((*FindExchangesResponse)(nil), "v2.FindExchangesResponse")
	proto.RegisterType((*DeleteExchangesRequest)(nil), "v2.DeleteExchangesRequest")
	proto.RegisterType((*DeleteExchangesResponse)(nil), "v2.DeleteExchangesResponse")
}

func init() { proto.RegisterFile("logging-service.proto", fileDescriptor_1fb7a78083aef92b) }

var fileDescriptor_1fb7a78083aef92b = []byte{
	// 931 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xbd, 0x6e, 0xc3, 0x54,
	0x14, 0x96, 0x13, 0x3b, 0x89, 0x4f, 0x1a, 0xda, 0x5e, 0x92, 0xd4, 0x35, 0x55, 0x29, 0x16, 0x43,
	0x84, 0x44, 0x2a, 0x85, 0xa5, 0x12, 0x50, 0xd1, 0xf4, 0x07, 0x15, 0x21, 0x06, 0xb7, 0xdd, 0xba,
	0xb8, 0xc9, 0xad, 0xb1, 0x70, 0xec, 0x60, 0x5f, 0x57, 0x94, 0x07, 0xe0, 0x39, 0x78, 0x04, 0xc4,
	0x13, 0x30, 0x30, 0x31, 0x32, 0x31, 0x30, 0x31, 0x33, 0x32, 0x32, 0xa0, 0xfb, 0xe3, 0xdf, 0xd8,
	0xae, 0x4a, 0x97, 0xb6, 0xb0, 0xf9, 0x9c, 0x7b, 0xcf, 0xf1, 0x3d, 0xdf, 0x77, 0xbe, 0xe3, 0x6b,
	0x18, 0xb8, 0xbe, 0x6d, 0x3b, 0x9e, 0xfd, 0x7e, 0x88, 0x83, 0x3b, 0x67, 0x86, 0xc7, 0xcb, 0xc0,
	0x27, 0x3e, 0x6a, 0xdc, 0x4d, 0xf4, 0xb7, 0x6d, 0xdf, 0xb7, 0x5d, 0xbc, 0xcf, 0x3c, 0x37, 0xd1,
	0xed, 0x3e, 0x71, 0x16, 0x38, 0x24, 0xd6, 0x62, 0xc9, 0x37, 0x19, 0xdf, 0x49, 0x20, 0x5f, 0x85,
	0x38, 0x40, 0x07, 0xa0, 0xce, 0x02, 0x6c, 0x11, 0x3c, 0x3f, 0x22, 0x9a, 0xb4, 0x27, 0x8d, 0xba,
	0x13, 0x7d, 0xcc, 0xa3, 0xc7, 0x71, 0xf4, 0xf8, 0x32, 0x8e, 0x36, 0xd3, 0xcd, 0x68, 0x08, 0xad,
	0x28, 0xc4, 0xc1, 0xf9, 0x5c, 0x6b, 0xec, 0x49, 0xa3, 0xa6, 0x29, 0x2c, 0x84, 0x40, 0x26, 0xf7,
	0x4b, 0xac, 0x35, 0xf7, 0xa4, 0x91, 0x6a, 0xb2, 0x67, 0xa4, 0x41, 0x7b, 0xe6, 0x7b, 0x04, 0x7b,
	0x44, 0x93, 0x99, 0x3b, 0x36, 0x8d, 0x63, 0xd8, 0x3c, 0x66, 0x29, 0xe9, 0x69, 0x4c, 0xfc, 0x75,
	0x84, 0x43, 0x82, 0x36, 0xa0, 0x69, 0x2d, 0x1d, 0x76, 0x1c, 0xd5, 0xa4, 0x8f, 0x68, 0x07, 0x64,
	0x9a, 0x9e, 0xbd, 0xaa, 0x3b, 0xe9, 0x8c, 0xef, 0x26, 0x63, 0x16, 0xc0, 0xbc, 0xc6, 0x21, 0xa0,
	0x6c, 0x92, 0x70, 0xe9, 0x7b, 0x21, 0x2e, 0xc9, 0x32, 0x84, 0x56, 0x48, 0x2c, 0x12, 0x85, 0x2c,
	0x8f, 0x62, 0x0a, 0xcb, 0xf8, 0xb1, 0x01, 0x1b, 0x67, 0x8e, 0x37, 0xa7, 0xe1, 0x61, 0xf5, 0x21,
	0x3e, 0x81, 0x5e, 0x52, 0xfe, 0x59, 0xe0, 0x2f, 0xc4, 0x69, 0xea, 0xf0, 0xca, 0x07, 0xa0, 0x8f,
	0xa0, 0x9b, 0x38, 0x2e, 0x7d, 0x06, 0x51, 0x7d, 0x7c, 0x76, 0x7b, 0x06, 0x71, 0xb9, 0x14, 0x71,
	0xa5, 0x1c, 0xf1, 0x56, 0x0e, 0x71, 0xd4, 0x07, 0xc5, 0x75, 0x16, 0x0e, 0xd1, 0xda, 0x0c, 0x03,
	0x6e, 0xd0, 0xdc, 0xfe, 0xed, 0x6d, 0x88, 0x89, 0xd6, 0xe1, 0xd0, 0x70, 0x8b, 0xe6, 0xf1, 0x83,
	0x39, 0x0e, 0xa6, 0xf7, 0x9a, 0xca, 0xf3, 0x08, 0xd3, 0x38, 0x85, 0xcd, 0x0c, 0x66, 0x95, 0x98,
	0xef, 0x82, 0x42, 0x8f, 0x49, 0x21, 0x6f, 0xe6, 0xa8, 0xe3, 0x6e, 0xe3, 0x57, 0x09, 0xd0, 0x09,
	0x76, 0x31, 0x27, 0xef, 0x75, 0xa0, 0x6f, 0x7c, 0x0c, 0x6f, 0xe6, 0x6a, 0xaa, 0x44, 0xa7, 0x0f,
	0xca, 0xcc, 0x8f, 0x3c, 0x22, 0x34, 0xc4, 0x0d, 0xe3, 0x07, 0x09, 0x64, 0x33, 0x72, 0xf1, 0xd3,
	0xd4, 0x19, 0x44, 0x2e, 0x4e, 0xd5, 0xc9, 0x2d, 0xb4, 0x93, 0x64, 0x9c, 0xde, 0x33, 0x04, 0x9a,
	0x66, 0xea, 0x40, 0xbb, 0x00, 0x74, 0xdf, 0x17, 0xd1, 0xe2, 0x06, 0x07, 0xa2, 0xce, 0x8c, 0x27,
	0xdb, 0x55, 0x4a, 0x85, 0x8e, 0xe9, 0xb9, 0x6b, 0x75, 0x4c, 0xd3, 0x65, 0x75, 0xcc, 0x02, 0x98,
	0x37, 0xd5, 0x31, 0x4f, 0xf2, 0x68, 0x1d, 0xff, 0x2e, 0x74, 0x4c, 0xc3, 0x9f, 0x77, 0x27, 0x09,
	0x6e, 0xe4, 0x6a, 0x6e, 0x94, 0x7a, 0x6e, 0x5a, 0x75, 0xdc, 0xb4, 0x2b, 0x14, 0xdf, 0x29, 0x57,
	0xbc, 0x5a, 0xa5, 0x78, 0x28, 0x55, 0xbc, 0x40, 0xb7, 0x4e, 0xf1, 0xf4, 0x58, 0x39, 0xc5, 0x33,
	0x42, 0xb9, 0xdb, 0xf8, 0x3b, 0x51, 0xfc, 0x7f, 0x91, 0xa7, 0x74, 0x36, 0x3c, 0x84, 0x63, 0xf9,
	0x6c, 0xf8, 0x4b, 0x82, 0xce, 0xe9, 0x37, 0xb3, 0x2f, 0x2d, 0xcf, 0x7e, 0xe2, 0x7c, 0xa0, 0x93,
	0x4a, 0xcc, 0x07, 0xc5, 0x14, 0x16, 0x65, 0x9f, 0x8a, 0x89, 0x2e, 0x34, 0xd9, 0x42, 0x6c, 0xd2,
	0xaa, 0x03, 0x4e, 0x55, 0x02, 0x48, 0xea, 0x40, 0xef, 0x42, 0x6f, 0x8e, 0x67, 0xae, 0x15, 0x58,
	0xc4, 0xf1, 0xbd, 0xf3, 0xb9, 0xc0, 0x25, 0xef, 0x64, 0xd8, 0x60, 0xdb, 0x09, 0x09, 0x9b, 0xa3,
	0xfc, 0xc3, 0x94, 0xf1, 0x54, 0xf7, 0xb0, 0x71, 0x01, 0x03, 0x3e, 0x1a, 0xe2, 0xda, 0xab, 0xdb,
	0x66, 0x04, 0x1d, 0x2c, 0x36, 0x89, 0x8e, 0x59, 0xa3, 0x2d, 0x98, 0x04, 0x26, 0xab, 0xc6, 0x14,
	0x86, 0xc5, 0xa4, 0x8f, 0x9e, 0x39, 0xdf, 0x37, 0xa1, 0x4f, 0x55, 0x11, 0xa7, 0x78, 0xde, 0xfd,
	0x2c, 0x38, 0x97, 0xab, 0x38, 0x57, 0x6a, 0x38, 0x6f, 0x3d, 0xc8, 0x79, 0xfb, 0x61, 0xce, 0x3b,
	0x75, 0x9c, 0xab, 0x15, 0x73, 0x0b, 0xca, 0xe7, 0x56, 0xb7, 0x6a, 0x6e, 0xad, 0xe5, 0xe7, 0xd6,
	0x15, 0x0c, 0x0a, 0x0c, 0x55, 0xb2, 0xfc, 0x1e, 0xa8, 0x71, 0x77, 0xc4, 0xf3, 0x2b, 0xdf, 0x3c,
	0xe9, 0xb2, 0xf1, 0x53, 0x03, 0x86, 0x5c, 0xc9, 0xff, 0x73, 0xff, 0xef, 0xb8, 0x37, 0x8e, 0x60,
	0x6b, 0x05, 0xc1, 0xc7, 0xcd, 0xc3, 0xc9, 0xcf, 0x12, 0x74, 0xe9, 0x2d, 0xeb, 0x82, 0xff, 0x04,
	0xa1, 0x0f, 0x01, 0xd2, 0x7f, 0x01, 0x34, 0xa0, 0xe4, 0xad, 0xfc, 0x60, 0xe8, 0xc3, 0xa2, 0x5b,
	0xbc, 0xf4, 0x00, 0xd4, 0xe4, 0x4e, 0x8b, 0xfa, 0x74, 0x53, 0xf1, 0xb7, 0x40, 0x1f, 0x14, 0xbc,
	0x22, 0xf2, 0x10, 0xba, 0x99, 0x1b, 0x1f, 0x62, 0x2f, 0x58, 0xbd, 0xd6, 0xea, 0x5b, 0x2b, 0x7e,
	0x1e, 0xcf, 0xca, 0xa0, 0x1f, 0x84, 0x95, 0x32, 0xd8, 0x3d, 0x30, 0x53, 0x46, 0xe6, 0x7e, 0x95,
	0x2d, 0x23, 0x77, 0x63, 0x12, 0x65, 0xb0, 0x0f, 0x4c, 0x5a, 0x46, 0xf6, 0x6b, 0x9b, 0x96, 0x91,
	0xff, 0x0a, 0x25, 0x65, 0xf0, 0xd8, 0x4c, 0x19, 0xb9, 0xe8, 0xad, 0x15, 0xbf, 0x28, 0xe3, 0x4f,
	0x09, 0xd6, 0x63, 0x2e, 0xe3, 0x52, 0x3e, 0x85, 0x37, 0xf2, 0x53, 0x16, 0x6d, 0xa7, 0xe7, 0x2e,
	0x8c, 0x73, 0x5d, 0x2f, 0x5b, 0x12, 0x87, 0x3b, 0x81, 0x5e, 0x4e, 0xc7, 0x48, 0x8b, 0x8b, 0x28,
	0x0a, 0x50, 0xdf, 0x2e, 0x59, 0x11, 0x59, 0x3e, 0x83, 0xf5, 0x42, 0xcf, 0x21, 0x3d, 0x2d, 0x67,
	0x25, 0xd3, 0x5b, 0xa5, 0x6b, 0xa2, 0xdc, 0xdf, 0x64, 0xe8, 0x7d, 0xce, 0xfe, 0xc2, 0x5f, 0x76,
	0xfb, 0xbd, 0xd0, 0x76, 0x7b, 0xc5, 0xad, 0x35, 0x7d, 0xe7, 0x97, 0x86, 0xea, 0x59, 0xdf, 0x7e,
	0x75, 0xed, 0xfa, 0x76, 0xf8, 0x47, 0x03, 0x25, 0xcf, 0xd7, 0x0b, 0x4c, 0xac, 0xb9, 0x45, 0xac,
	0x9b, 0x16, 0x1b, 0xfa, 0x1f, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x3b, 0x29, 0x04, 0x09,
	0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error)
	DeleteUsers(ctx context.Context, in *DeleteUsersRequest, opts ...grpc.CallOption) (*DeleteUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/v2.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error) {
	out := new(FindUsersResponse)
	err := c.cc.Invoke(ctx, "/v2.UserService/FindUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUsers(ctx context.Context, in *DeleteUsersRequest, opts ...grpc.CallOption) (*DeleteUsersResponse, error) {
	out := new(DeleteUsersResponse)
	err := c.cc.Invoke(ctx, "/v2.UserService/DeleteUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUsers(context.Context, *FindUsersRequest) (*FindUsersResponse, error)
	DeleteUsers(context.Context, *DeleteUsersRequest) (*DeleteUsersResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.UserService/FindUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindUsers(ctx, req.(*FindUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.UserService/DeleteUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUsers(ctx, req.(*DeleteUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "FindUsers",
			Handler:    _UserService_FindUsers_Handler,
		},
		{
			MethodName: "DeleteUsers",
			Handler:    _UserService_DeleteUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// RuleServiceClient is the client API for RuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuleServiceClient interface {
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error)
	FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error)
	DeleteRules(ctx context.Context, in *DeleteRulesRequest, opts ...grpc.CallOption) (*DeleteRulesResponse, error)
}

type ruleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuleServiceClient(cc *grpc.ClientConn) RuleServiceClient {
	return &ruleServiceClient{cc}
}

func (c *ruleServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error) {
	out := new(CreateRuleResponse)
	err := c.cc.Invoke(ctx, "/v2.RuleService/CreateRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error) {
	out := new(FindRulesResponse)
	err := c.cc.Invoke(ctx, "/v2.RuleService/FindRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) DeleteRules(ctx context.Context, in *DeleteRulesRequest, opts ...grpc.CallOption) (*DeleteRulesResponse, error) {
	out := new(DeleteRulesResponse)
	err := c.cc.Invoke(ctx, "/v2.RuleService/DeleteRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServiceServer is the server API for RuleService service.
type RuleServiceServer interface {
	CreateRule(context.Context, *CreateRuleRequest) (*CreateRuleResponse, error)
	FindRules(context.Context, *FindRulesRequest) (*FindRulesResponse, error)
	DeleteRules(context.Context, *DeleteRulesRequest) (*DeleteRulesResponse, error)
}

func RegisterRuleServiceServer(s *grpc.Server, srv RuleServiceServer) {
	s.RegisterService(&_RuleService_serviceDesc, srv)
}

func _RuleService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.RuleService/CreateRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_FindRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).FindRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.RuleService/FindRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).FindRules(ctx, req.(*FindRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_DeleteRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).DeleteRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.RuleService/DeleteRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).DeleteRules(ctx, req.(*DeleteRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.RuleService",
	HandlerType: (*RuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRule",
			Handler:    _RuleService_CreateRule_Handler,
		},
		{
			MethodName: "FindRules",
			Handler:    _RuleService_FindRules_Handler,
		},
		{
			MethodName: "DeleteRules",
			Handler:    _RuleService_DeleteRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// ExchangeServiceClient is the client API for ExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeServiceClient interface {
	CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error)
	FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error)
	DeleteExchanges(ctx context.Context, in *DeleteExchangesRequest, opts ...grpc.CallOption) (*DeleteExchangesResponse, error)
}

type exchangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewExchangeServiceClient(cc *grpc.ClientConn) ExchangeServiceClient {
	return &exchangeServiceClient{cc}
}

func (c *exchangeServiceClient) CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error) {
	out := new(CreateExchangeResponse)
	err := c.cc.Invoke(ctx, "/v2.ExchangeService/CreateExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error) {
	out := new(FindExchangesResponse)
	err := c.cc.Invoke(ctx, "/v2.ExchangeService/FindExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) DeleteExchanges(ctx context.Context, in *DeleteExchangesRequest, opts ...grpc.CallOption) (*DeleteExchangesResponse, error) {
	out := new(DeleteExchangesResponse)
	err := c.cc.Invoke(ctx, "/v2.ExchangeService/DeleteExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeServiceServer is the server API for ExchangeService service.
type ExchangeServiceServer interface {
	CreateExchange(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error)
	FindExchanges(context.Context, *FindExchangesRequest) (*FindExchangesResponse, error)
	DeleteExchanges(context.Context, *DeleteExchangesRequest) (*DeleteExchangesResponse, error)
}

func RegisterExchangeServiceServer(s *grpc.Server, srv ExchangeServiceServer) {
	s.RegisterService(&_ExchangeService_serviceDesc, srv)
}

func _ExchangeService_CreateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).CreateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.ExchangeService/CreateExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).CreateExchange(ctx, req.(*CreateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_FindExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).FindExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.ExchangeService/FindExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).FindExchanges(ctx, req.(*FindExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_DeleteExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).DeleteExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.ExchangeService/DeleteExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).DeleteExchanges(ctx, req.(*DeleteExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExchangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.ExchangeService",
	HandlerType: (*ExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExchange",
			Handler:    _ExchangeService_CreateExchange_Handler,
		},
		{
			MethodName: "FindExchanges",
			Handler:    _ExchangeService_FindExchanges_Handler,
		},
		{
			MethodName: "DeleteExchanges",
			Handler:    _ExchangeService_DeleteExchanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// LogginServiceClient is the client API for LogginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogginServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error)
	DeleteUsers(ctx context.Context, in *DeleteUsersRequest, opts ...grpc.CallOption) (*DeleteUsersResponse, error)
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error)
	FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error)
	DeleteRules(ctx context.Context, in *DeleteRulesRequest, opts ...grpc.CallOption) (*DeleteRulesResponse, error)
	CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error)
	FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error)
	DeleteExchanges(ctx context.Context, in *DeleteExchangesRequest, opts ...grpc.CallOption) (*DeleteExchangesResponse, error)
}

type logginServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogginServiceClient(cc *grpc.ClientConn) LogginServiceClient {
	return &logginServiceClient{cc}
}

func (c *logginServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindUsers(ctx context.Context, in *FindUsersRequest, opts ...grpc.CallOption) (*FindUsersResponse, error) {
	out := new(FindUsersResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) DeleteUsers(ctx context.Context, in *DeleteUsersRequest, opts ...grpc.CallOption) (*DeleteUsersResponse, error) {
	out := new(DeleteUsersResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/DeleteUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*CreateRuleResponse, error) {
	out := new(CreateRuleResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindRules(ctx context.Context, in *FindRulesRequest, opts ...grpc.CallOption) (*FindRulesResponse, error) {
	out := new(FindRulesResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) DeleteRules(ctx context.Context, in *DeleteRulesRequest, opts ...grpc.CallOption) (*DeleteRulesResponse, error) {
	out := new(DeleteRulesResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/DeleteRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error) {
	out := new(CreateExchangeResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/CreateExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) FindExchanges(ctx context.Context, in *FindExchangesRequest, opts ...grpc.CallOption) (*FindExchangesResponse, error) {
	out := new(FindExchangesResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/FindExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logginServiceClient) DeleteExchanges(ctx context.Context, in *DeleteExchangesRequest, opts ...grpc.CallOption) (*DeleteExchangesResponse, error) {
	out := new(DeleteExchangesResponse)
	err := c.cc.Invoke(ctx, "/v2.LogginService/DeleteExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogginServiceServer is the server API for LogginService service.
type LogginServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	FindUsers(context.Context, *FindUsersRequest) (*FindUsersResponse, error)
	DeleteUsers(context.Context, *DeleteUsersRequest) (*DeleteUsersResponse, error)
	CreateRule(context.Context, *CreateRuleRequest) (*CreateRuleResponse, error)
	FindRules(context.Context, *FindRulesRequest) (*FindRulesResponse, error)
	DeleteRules(context.Context, *DeleteRulesRequest) (*DeleteRulesResponse, error)
	CreateExchange(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error)
	FindExchanges(context.Context, *FindExchangesRequest) (*FindExchangesResponse, error)
	DeleteExchanges(context.Context, *DeleteExchangesRequest) (*DeleteExchangesResponse, error)
}

func RegisterLogginServiceServer(s *grpc.Server, srv LogginServiceServer) {
	s.RegisterService(&_LogginService_serviceDesc, srv)
}

func _LogginService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindUsers(ctx, req.(*FindUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_DeleteUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).DeleteUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/DeleteUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).DeleteUsers(ctx, req.(*DeleteUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindRules(ctx, req.(*FindRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_DeleteRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).DeleteRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/DeleteRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).DeleteRules(ctx, req.(*DeleteRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_CreateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).CreateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/CreateExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).CreateExchange(ctx, req.(*CreateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_FindExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).FindExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/FindExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).FindExchanges(ctx, req.(*FindExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogginService_DeleteExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogginServiceServer).DeleteExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v2.LogginService/DeleteExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogginServiceServer).DeleteExchanges(ctx, req.(*DeleteExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v2.LogginService",
	HandlerType: (*LogginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _LogginService_CreateUser_Handler,
		},
		{
			MethodName: "FindUsers",
			Handler:    _LogginService_FindUsers_Handler,
		},
		{
			MethodName: "DeleteUsers",
			Handler:    _LogginService_DeleteUsers_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _LogginService_CreateRule_Handler,
		},
		{
			MethodName: "FindRules",
			Handler:    _LogginService_FindRules_Handler,
		},
		{
			MethodName: "DeleteRules",
			Handler:    _LogginService_DeleteRules_Handler,
		},
		{
			MethodName: "CreateExchange",
			Handler:    _LogginService_CreateExchange_Handler,
		},
		{
			MethodName: "FindExchanges",
			Handler:    _LogginService_FindExchanges_Handler,
		},
		{
			MethodName: "DeleteExchanges",
			Handler:    _LogginService_DeleteExchanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}
