// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logging-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ---------------------- << USER LOGS >>
type UserLog struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,3,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	Type                 string               `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Message              string               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserLog) Reset()         { *m = UserLog{} }
func (m *UserLog) String() string { return proto.CompactTextString(m) }
func (*UserLog) ProtoMessage()    {}
func (*UserLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{0}
}

func (m *UserLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLog.Unmarshal(m, b)
}
func (m *UserLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLog.Marshal(b, m, deterministic)
}
func (m *UserLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLog.Merge(m, src)
}
func (m *UserLog) XXX_Size() int {
	return xxx_messageInfo_UserLog.Size(m)
}
func (m *UserLog) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLog.DiscardUnknown(m)
}

var xxx_messageInfo_UserLog proto.InternalMessageInfo

func (m *UserLog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserLog) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserLog) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *UserLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserLog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// CREATE
type CreateUserLogRequest struct {
	// API versioning
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UserLog              *UserLog `protobuf:"bytes,2,opt,name=userLog,proto3" json:"userLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserLogRequest) Reset()         { *m = CreateUserLogRequest{} }
func (m *CreateUserLogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserLogRequest) ProtoMessage()    {}
func (*CreateUserLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{1}
}

func (m *CreateUserLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserLogRequest.Unmarshal(m, b)
}
func (m *CreateUserLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserLogRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserLogRequest.Merge(m, src)
}
func (m *CreateUserLogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserLogRequest.Size(m)
}
func (m *CreateUserLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserLogRequest proto.InternalMessageInfo

func (m *CreateUserLogRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserLogRequest) GetUserLog() *UserLog {
	if m != nil {
		return m.UserLog
	}
	return nil
}

type CreateUserLogResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserLogResponse) Reset()         { *m = CreateUserLogResponse{} }
func (m *CreateUserLogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserLogResponse) ProtoMessage()    {}
func (*CreateUserLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{2}
}

func (m *CreateUserLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserLogResponse.Unmarshal(m, b)
}
func (m *CreateUserLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserLogResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserLogResponse.Merge(m, src)
}
func (m *CreateUserLogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserLogResponse.Size(m)
}
func (m *CreateUserLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserLogResponse proto.InternalMessageInfo

func (m *CreateUserLogResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserLogResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// READ
type ReadUserLogRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserLogRequest) Reset()         { *m = ReadUserLogRequest{} }
func (m *ReadUserLogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserLogRequest) ProtoMessage()    {}
func (*ReadUserLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{3}
}

func (m *ReadUserLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserLogRequest.Unmarshal(m, b)
}
func (m *ReadUserLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserLogRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserLogRequest.Merge(m, src)
}
func (m *ReadUserLogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserLogRequest.Size(m)
}
func (m *ReadUserLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserLogRequest proto.InternalMessageInfo

func (m *ReadUserLogRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadUserLogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadUserLogResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UserLog              *UserLog `protobuf:"bytes,2,opt,name=userLog,proto3" json:"userLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserLogResponse) Reset()         { *m = ReadUserLogResponse{} }
func (m *ReadUserLogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserLogResponse) ProtoMessage()    {}
func (*ReadUserLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{4}
}

func (m *ReadUserLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserLogResponse.Unmarshal(m, b)
}
func (m *ReadUserLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserLogResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserLogResponse.Merge(m, src)
}
func (m *ReadUserLogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserLogResponse.Size(m)
}
func (m *ReadUserLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserLogResponse proto.InternalMessageInfo

func (m *ReadUserLogResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadUserLogResponse) GetUserLog() *UserLog {
	if m != nil {
		return m.UserLog
	}
	return nil
}

// FIND LOGS
type FindUserLogsRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,5,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	Type                 string               `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Limit                int32                `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindUserLogsRequest) Reset()         { *m = FindUserLogsRequest{} }
func (m *FindUserLogsRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserLogsRequest) ProtoMessage()    {}
func (*FindUserLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{5}
}

func (m *FindUserLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserLogsRequest.Unmarshal(m, b)
}
func (m *FindUserLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserLogsRequest.Marshal(b, m, deterministic)
}
func (m *FindUserLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserLogsRequest.Merge(m, src)
}
func (m *FindUserLogsRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserLogsRequest.Size(m)
}
func (m *FindUserLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserLogsRequest proto.InternalMessageInfo

func (m *FindUserLogsRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUserLogsRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *FindUserLogsRequest) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *FindUserLogsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FindUserLogsRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *FindUserLogsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FindUserLogsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindUserLogsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type FindUserLogsResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UserLogs             []*UserLog `protobuf:"bytes,2,rep,name=userLogs,proto3" json:"userLogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindUserLogsResponse) Reset()         { *m = FindUserLogsResponse{} }
func (m *FindUserLogsResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserLogsResponse) ProtoMessage()    {}
func (*FindUserLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{6}
}

func (m *FindUserLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserLogsResponse.Unmarshal(m, b)
}
func (m *FindUserLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserLogsResponse.Marshal(b, m, deterministic)
}
func (m *FindUserLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserLogsResponse.Merge(m, src)
}
func (m *FindUserLogsResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserLogsResponse.Size(m)
}
func (m *FindUserLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserLogsResponse proto.InternalMessageInfo

func (m *FindUserLogsResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUserLogsResponse) GetUserLogs() []*UserLog {
	if m != nil {
		return m.UserLogs
	}
	return nil
}

// EXCHANGES
type ExchangeLog struct {
	TypeId               int64                `protobuf:"varint,1,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int64                `protobuf:"varint,2,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,4,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,5,opt,name=registerId,proto3" json:"registerId,omitempty"`
	Content              string               `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExchangeLog) Reset()         { *m = ExchangeLog{} }
func (m *ExchangeLog) String() string { return proto.CompactTextString(m) }
func (*ExchangeLog) ProtoMessage()    {}
func (*ExchangeLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{7}
}

func (m *ExchangeLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeLog.Unmarshal(m, b)
}
func (m *ExchangeLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeLog.Marshal(b, m, deterministic)
}
func (m *ExchangeLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeLog.Merge(m, src)
}
func (m *ExchangeLog) XXX_Size() int {
	return xxx_messageInfo_ExchangeLog.Size(m)
}
func (m *ExchangeLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeLog.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeLog proto.InternalMessageInfo

func (m *ExchangeLog) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *ExchangeLog) GetStateId() int64 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *ExchangeLog) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *ExchangeLog) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *ExchangeLog) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *ExchangeLog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ExchangeLog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateExchangeLogRequest struct {
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ExchageLog           *ExchangeLog `protobuf:"bytes,2,opt,name=exchageLog,proto3" json:"exchageLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateExchangeLogRequest) Reset()         { *m = CreateExchangeLogRequest{} }
func (m *CreateExchangeLogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeLogRequest) ProtoMessage()    {}
func (*CreateExchangeLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{8}
}

func (m *CreateExchangeLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeLogRequest.Unmarshal(m, b)
}
func (m *CreateExchangeLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeLogRequest.Marshal(b, m, deterministic)
}
func (m *CreateExchangeLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeLogRequest.Merge(m, src)
}
func (m *CreateExchangeLogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeLogRequest.Size(m)
}
func (m *CreateExchangeLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeLogRequest proto.InternalMessageInfo

func (m *CreateExchangeLogRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateExchangeLogRequest) GetExchageLog() *ExchangeLog {
	if m != nil {
		return m.ExchageLog
	}
	return nil
}

type CreateExchangeLogResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateExchangeLogResponse) Reset()         { *m = CreateExchangeLogResponse{} }
func (m *CreateExchangeLogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeLogResponse) ProtoMessage()    {}
func (*CreateExchangeLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{9}
}

func (m *CreateExchangeLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeLogResponse.Unmarshal(m, b)
}
func (m *CreateExchangeLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeLogResponse.Marshal(b, m, deterministic)
}
func (m *CreateExchangeLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeLogResponse.Merge(m, src)
}
func (m *CreateExchangeLogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeLogResponse.Size(m)
}
func (m *CreateExchangeLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeLogResponse proto.InternalMessageInfo

func (m *CreateExchangeLogResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateExchangeLogResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FindExchangeLogsRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	TypeId               int64                `protobuf:"varint,4,opt,name=typeId,proto3" json:"typeId,omitempty"`
	StateId              int64                `protobuf:"varint,5,opt,name=stateId,proto3" json:"stateId,omitempty"`
	RequestId            int64                `protobuf:"varint,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,7,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	RegisterId           string               `protobuf:"bytes,8,opt,name=registerId,proto3" json:"registerId,omitempty"`
	Content              string               `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Limit                int64                `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64                `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy              string               `protobuf:"bytes,12,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindExchangeLogsRequest) Reset()         { *m = FindExchangeLogsRequest{} }
func (m *FindExchangeLogsRequest) String() string { return proto.CompactTextString(m) }
func (*FindExchangeLogsRequest) ProtoMessage()    {}
func (*FindExchangeLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{10}
}

func (m *FindExchangeLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindExchangeLogsRequest.Unmarshal(m, b)
}
func (m *FindExchangeLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindExchangeLogsRequest.Marshal(b, m, deterministic)
}
func (m *FindExchangeLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindExchangeLogsRequest.Merge(m, src)
}
func (m *FindExchangeLogsRequest) XXX_Size() int {
	return xxx_messageInfo_FindExchangeLogsRequest.Size(m)
}
func (m *FindExchangeLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindExchangeLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindExchangeLogsRequest proto.InternalMessageInfo

func (m *FindExchangeLogsRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindExchangeLogsRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *FindExchangeLogsRequest) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *FindExchangeLogsRequest) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *FindExchangeLogsRequest) GetStateId() int64 {
	if m != nil {
		return m.StateId
	}
	return 0
}

func (m *FindExchangeLogsRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *FindExchangeLogsRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *FindExchangeLogsRequest) GetRegisterId() string {
	if m != nil {
		return m.RegisterId
	}
	return ""
}

func (m *FindExchangeLogsRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FindExchangeLogsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindExchangeLogsRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindExchangeLogsRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type FindExchangeLogsResponse struct {
	Api                  string         `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ExchageLogs          []*ExchangeLog `protobuf:"bytes,2,rep,name=exchageLogs,proto3" json:"exchageLogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindExchangeLogsResponse) Reset()         { *m = FindExchangeLogsResponse{} }
func (m *FindExchangeLogsResponse) String() string { return proto.CompactTextString(m) }
func (*FindExchangeLogsResponse) ProtoMessage()    {}
func (*FindExchangeLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{11}
}

func (m *FindExchangeLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindExchangeLogsResponse.Unmarshal(m, b)
}
func (m *FindExchangeLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindExchangeLogsResponse.Marshal(b, m, deterministic)
}
func (m *FindExchangeLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindExchangeLogsResponse.Merge(m, src)
}
func (m *FindExchangeLogsResponse) XXX_Size() int {
	return xxx_messageInfo_FindExchangeLogsResponse.Size(m)
}
func (m *FindExchangeLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindExchangeLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindExchangeLogsResponse proto.InternalMessageInfo

func (m *FindExchangeLogsResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindExchangeLogsResponse) GetExchageLogs() []*ExchangeLog {
	if m != nil {
		return m.ExchageLogs
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLog)(nil), "v1.UserLog")
	proto.RegisterType((*CreateUserLogRequest)(nil), "v1.CreateUserLogRequest")
	proto.RegisterType((*CreateUserLogResponse)(nil), "v1.CreateUserLogResponse")
	proto.RegisterType((*ReadUserLogRequest)(nil), "v1.ReadUserLogRequest")
	proto.RegisterType((*ReadUserLogResponse)(nil), "v1.ReadUserLogResponse")
	proto.RegisterType((*FindUserLogsRequest)(nil), "v1.FindUserLogsRequest")
	proto.RegisterType((*FindUserLogsResponse)(nil), "v1.FindUserLogsResponse")
	proto.RegisterType((*ExchangeLog)(nil), "v1.ExchangeLog")
	proto.RegisterType((*CreateExchangeLogRequest)(nil), "v1.CreateExchangeLogRequest")
	proto.RegisterType((*CreateExchangeLogResponse)(nil), "v1.CreateExchangeLogResponse")
	proto.RegisterType((*FindExchangeLogsRequest)(nil), "v1.FindExchangeLogsRequest")
	proto.RegisterType((*FindExchangeLogsResponse)(nil), "v1.FindExchangeLogsResponse")
}

func init() { proto.RegisterFile("logging-service.proto", fileDescriptor_1fb7a78083aef92b) }

var fileDescriptor_1fb7a78083aef92b = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x96, 0x9d, 0x57, 0x33, 0x6e, 0x4b, 0xd9, 0xb6, 0xe9, 0xd6, 0x14, 0x88, 0x2c, 0x10, 0x11,
	0x12, 0xae, 0x1a, 0x24, 0x04, 0x17, 0xa4, 0x02, 0x45, 0xaa, 0xc4, 0xd3, 0xc0, 0x11, 0x21, 0x37,
	0xde, 0x18, 0x4b, 0x89, 0x37, 0x78, 0x37, 0x15, 0x3d, 0xf3, 0x9b, 0x38, 0xf3, 0x3b, 0xf8, 0x25,
	0x1c, 0x41, 0xfb, 0x4a, 0x9c, 0xd8, 0x4e, 0xe1, 0xc4, 0xcd, 0xf3, 0xd8, 0xd9, 0x99, 0x6f, 0xbe,
	0x6f, 0x0d, 0xbb, 0x23, 0x1a, 0xc7, 0x49, 0x1a, 0xdf, 0x63, 0x24, 0x3b, 0x4f, 0x06, 0xc4, 0x9f,
	0x64, 0x94, 0x53, 0x64, 0x9f, 0x1f, 0xb9, 0x37, 0x63, 0x4a, 0xe3, 0x11, 0x39, 0x94, 0x9e, 0xb3,
	0xe9, 0xf0, 0x90, 0x27, 0x63, 0xc2, 0x78, 0x38, 0x9e, 0xa8, 0x24, 0xef, 0x87, 0x05, 0xad, 0x0f,
	0x8c, 0x64, 0x2f, 0x68, 0x8c, 0x36, 0xc1, 0x4e, 0x22, 0x6c, 0x75, 0xad, 0x5e, 0x2d, 0xb0, 0x93,
	0x08, 0x75, 0xa0, 0x39, 0x65, 0x24, 0x3b, 0x8d, 0xb0, 0x2d, 0x7d, 0xda, 0x42, 0xb7, 0x60, 0x23,
	0x22, 0x83, 0x51, 0x98, 0x85, 0x3c, 0xa1, 0xe9, 0x69, 0x84, 0x6b, 0x32, 0xbc, 0xe8, 0x44, 0x08,
	0xea, 0xfc, 0x62, 0x42, 0x70, 0xbd, 0x6b, 0xf5, 0xda, 0x81, 0xfc, 0x46, 0x18, 0x5a, 0x63, 0xc2,
	0x58, 0x18, 0x13, 0xdc, 0x90, 0x6e, 0x63, 0xa2, 0x87, 0xd0, 0x1e, 0x64, 0x24, 0xe4, 0x24, 0x3a,
	0xe6, 0xb8, 0xd9, 0xb5, 0x7a, 0x4e, 0xdf, 0xf5, 0x55, 0xf3, 0xbe, 0x69, 0xde, 0x7f, 0x6f, 0x9a,
	0x0f, 0xe6, 0xc9, 0xde, 0x6b, 0xd8, 0x79, 0x2a, 0x0d, 0x3d, 0x46, 0x40, 0xbe, 0x4c, 0x09, 0xe3,
	0x68, 0x0b, 0x6a, 0xe1, 0x24, 0x91, 0xe3, 0xb4, 0x03, 0xf1, 0x89, 0x6e, 0x43, 0x6b, 0xaa, 0x72,
	0xe4, 0x40, 0x4e, 0xdf, 0xf1, 0xcf, 0x8f, 0x7c, 0x73, 0xcc, 0xc4, 0xbc, 0x47, 0xb0, 0xbb, 0x54,
	0x90, 0x4d, 0x68, 0xca, 0x48, 0x49, 0x45, 0x85, 0x98, 0x6d, 0x10, 0xf3, 0x1e, 0x00, 0x0a, 0x48,
	0x18, 0x5d, 0xda, 0xc9, 0xf2, 0xb9, 0x57, 0xb0, 0xbd, 0x70, 0xae, 0xf2, 0xc2, 0xbf, 0x1c, 0xe1,
	0x9b, 0x0d, 0xdb, 0xcf, 0x93, 0xd4, 0x14, 0x64, 0xd5, 0x9d, 0xf8, 0x50, 0x1f, 0x66, 0x74, 0xac,
	0xab, 0xad, 0x82, 0x5c, 0xe6, 0xa1, 0xbb, 0x60, 0x73, 0x2a, 0x17, 0xbe, 0x3a, 0xdb, 0xe6, 0x34,
	0xc7, 0x9f, 0xfa, 0x6a, 0xfe, 0x34, 0x56, 0xf1, 0xa7, 0x99, 0xe3, 0xcf, 0x0e, 0x34, 0x46, 0xc9,
	0x38, 0xe1, 0xb8, 0xd5, 0xb5, 0x7a, 0x8d, 0x40, 0x19, 0xe2, 0x1e, 0x3a, 0x1c, 0x32, 0xc2, 0xf1,
	0x9a, 0x74, 0x6b, 0xcb, 0x7b, 0x0b, 0x3b, 0x8b, 0x20, 0x54, 0xc2, 0x7a, 0x07, 0xd6, 0x34, 0x74,
	0x0c, 0xdb, 0xdd, 0xda, 0x32, 0xae, 0xb3, 0xa0, 0xf7, 0xcb, 0x02, 0xe7, 0xe4, 0xeb, 0xe0, 0x73,
	0x98, 0xc6, 0x44, 0x48, 0xa6, 0x03, 0x4d, 0xd1, 0xd8, 0xa9, 0x91, 0x8d, 0xb6, 0x04, 0xd1, 0x19,
	0x0f, 0x39, 0x99, 0x69, 0xc7, 0x98, 0xe8, 0x00, 0xda, 0x99, 0xda, 0xc6, 0x4c, 0x38, 0x73, 0x47,
	0x11, 0x9a, 0x7a, 0x19, 0x34, 0x37, 0x00, 0x32, 0x12, 0x27, 0x8c, 0x4b, 0x70, 0x95, 0x92, 0x72,
	0x1e, 0x71, 0xfb, 0x80, 0xa6, 0x9c, 0xa4, 0x5c, 0xa3, 0x67, 0xcc, 0x45, 0x99, 0xb5, 0xfe, 0x45,
	0x66, 0x1f, 0x01, 0x2b, 0x55, 0xe4, 0xc6, 0xaf, 0xa6, 0xd5, 0x21, 0x00, 0x11, 0x79, 0x32, 0x4d,
	0x93, 0xeb, 0x8a, 0x80, 0x34, 0x7f, 0x3a, 0x97, 0xe2, 0x9d, 0xc0, 0x7e, 0x49, 0xf9, 0xca, 0x85,
	0x75, 0xa0, 0x29, 0x00, 0x9d, 0x32, 0xf3, 0x34, 0x29, 0xcb, 0xfb, 0x6d, 0xc3, 0x9e, 0xd8, 0x79,
	0xae, 0xca, 0xff, 0x23, 0xbf, 0x66, 0x46, 0xbd, 0x8a, 0x19, 0x8d, 0x15, 0xcc, 0x68, 0x5e, 0xca,
	0x8c, 0xd6, 0xe5, 0xcc, 0x58, 0x5b, 0xc5, 0x8c, 0xf6, 0x22, 0x33, 0x66, 0xd2, 0x02, 0x59, 0xb7,
	0x20, 0x2d, 0x47, 0x4d, 0xa1, 0x2c, 0x51, 0x87, 0x66, 0x11, 0xc9, 0x9e, 0x5c, 0xe0, 0x75, 0x55,
	0x47, 0x9b, 0xde, 0x27, 0xc0, 0xc5, 0x05, 0x54, 0xee, 0xf1, 0x08, 0x9c, 0x39, 0x09, 0x8c, 0xf6,
	0x0a, 0x44, 0xc9, 0xe7, 0xf4, 0x7f, 0x5a, 0xb0, 0xa9, 0x85, 0xf9, 0x4e, 0xfd, 0xef, 0xd0, 0x33,
	0xd8, 0x58, 0x78, 0xb1, 0x11, 0x16, 0x15, 0xca, 0xfe, 0x0a, 0xee, 0x7e, 0x49, 0x44, 0x77, 0xf7,
	0x18, 0x9c, 0xdc, 0x23, 0x8c, 0x3a, 0x22, 0xb3, 0xf8, 0x9a, 0xbb, 0x7b, 0x05, 0xbf, 0x3e, 0x7f,
	0x0c, 0xeb, 0xf9, 0xe7, 0x06, 0xc9, 0xc4, 0x92, 0x57, 0xd8, 0xc5, 0xc5, 0x80, 0x2a, 0xd1, 0xff,
	0x6e, 0x01, 0xca, 0x0d, 0x6e, 0xe6, 0x7b, 0x03, 0x57, 0x0b, 0xe2, 0x40, 0x07, 0xf3, 0x49, 0x8a,
	0x92, 0x74, 0xaf, 0x57, 0x44, 0x75, 0xaf, 0x2f, 0x61, 0x6b, 0x79, 0x4b, 0xe8, 0x9a, 0x69, 0xab,
	0x44, 0x3c, 0xee, 0x41, 0x79, 0x50, 0x95, 0x3b, 0x6b, 0x4a, 0x11, 0xdc, 0xff, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x93, 0xb9, 0x7e, 0x88, 0x8a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserLogServiceClient is the client API for UserLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserLogServiceClient interface {
	CreateUserLog(ctx context.Context, in *CreateUserLogRequest, opts ...grpc.CallOption) (*CreateUserLogResponse, error)
	ReadUserLog(ctx context.Context, in *ReadUserLogRequest, opts ...grpc.CallOption) (*ReadUserLogResponse, error)
	FindUserLogs(ctx context.Context, in *FindUserLogsRequest, opts ...grpc.CallOption) (*FindUserLogsResponse, error)
}

type userLogServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserLogServiceClient(cc *grpc.ClientConn) UserLogServiceClient {
	return &userLogServiceClient{cc}
}

func (c *userLogServiceClient) CreateUserLog(ctx context.Context, in *CreateUserLogRequest, opts ...grpc.CallOption) (*CreateUserLogResponse, error) {
	out := new(CreateUserLogResponse)
	err := c.cc.Invoke(ctx, "/v1.UserLogService/CreateUserLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLogServiceClient) ReadUserLog(ctx context.Context, in *ReadUserLogRequest, opts ...grpc.CallOption) (*ReadUserLogResponse, error) {
	out := new(ReadUserLogResponse)
	err := c.cc.Invoke(ctx, "/v1.UserLogService/ReadUserLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLogServiceClient) FindUserLogs(ctx context.Context, in *FindUserLogsRequest, opts ...grpc.CallOption) (*FindUserLogsResponse, error) {
	out := new(FindUserLogsResponse)
	err := c.cc.Invoke(ctx, "/v1.UserLogService/FindUserLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLogServiceServer is the server API for UserLogService service.
type UserLogServiceServer interface {
	CreateUserLog(context.Context, *CreateUserLogRequest) (*CreateUserLogResponse, error)
	ReadUserLog(context.Context, *ReadUserLogRequest) (*ReadUserLogResponse, error)
	FindUserLogs(context.Context, *FindUserLogsRequest) (*FindUserLogsResponse, error)
}

func RegisterUserLogServiceServer(s *grpc.Server, srv UserLogServiceServer) {
	s.RegisterService(&_UserLogService_serviceDesc, srv)
}

func _UserLogService_CreateUserLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLogServiceServer).CreateUserLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserLogService/CreateUserLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLogServiceServer).CreateUserLog(ctx, req.(*CreateUserLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLogService_ReadUserLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLogServiceServer).ReadUserLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserLogService/ReadUserLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLogServiceServer).ReadUserLog(ctx, req.(*ReadUserLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLogService_FindUserLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLogServiceServer).FindUserLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserLogService/FindUserLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLogServiceServer).FindUserLogs(ctx, req.(*FindUserLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserLogService",
	HandlerType: (*UserLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserLog",
			Handler:    _UserLogService_CreateUserLog_Handler,
		},
		{
			MethodName: "ReadUserLog",
			Handler:    _UserLogService_ReadUserLog_Handler,
		},
		{
			MethodName: "FindUserLogs",
			Handler:    _UserLogService_FindUserLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}

// ExchangeLogServiceClient is the client API for ExchangeLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeLogServiceClient interface {
	CreateExchangeLog(ctx context.Context, in *CreateExchangeLogRequest, opts ...grpc.CallOption) (*CreateExchangeLogResponse, error)
	FindExchangeLogs(ctx context.Context, in *FindExchangeLogsRequest, opts ...grpc.CallOption) (*FindExchangeLogsResponse, error)
}

type exchangeLogServiceClient struct {
	cc *grpc.ClientConn
}

func NewExchangeLogServiceClient(cc *grpc.ClientConn) ExchangeLogServiceClient {
	return &exchangeLogServiceClient{cc}
}

func (c *exchangeLogServiceClient) CreateExchangeLog(ctx context.Context, in *CreateExchangeLogRequest, opts ...grpc.CallOption) (*CreateExchangeLogResponse, error) {
	out := new(CreateExchangeLogResponse)
	err := c.cc.Invoke(ctx, "/v1.ExchangeLogService/CreateExchangeLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeLogServiceClient) FindExchangeLogs(ctx context.Context, in *FindExchangeLogsRequest, opts ...grpc.CallOption) (*FindExchangeLogsResponse, error) {
	out := new(FindExchangeLogsResponse)
	err := c.cc.Invoke(ctx, "/v1.ExchangeLogService/FindExchangeLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeLogServiceServer is the server API for ExchangeLogService service.
type ExchangeLogServiceServer interface {
	CreateExchangeLog(context.Context, *CreateExchangeLogRequest) (*CreateExchangeLogResponse, error)
	FindExchangeLogs(context.Context, *FindExchangeLogsRequest) (*FindExchangeLogsResponse, error)
}

func RegisterExchangeLogServiceServer(s *grpc.Server, srv ExchangeLogServiceServer) {
	s.RegisterService(&_ExchangeLogService_serviceDesc, srv)
}

func _ExchangeLogService_CreateExchangeLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeLogServiceServer).CreateExchangeLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ExchangeLogService/CreateExchangeLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeLogServiceServer).CreateExchangeLog(ctx, req.(*CreateExchangeLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeLogService_FindExchangeLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindExchangeLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeLogServiceServer).FindExchangeLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ExchangeLogService/FindExchangeLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeLogServiceServer).FindExchangeLogs(ctx, req.(*FindExchangeLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExchangeLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ExchangeLogService",
	HandlerType: (*ExchangeLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExchangeLog",
			Handler:    _ExchangeLogService_CreateExchangeLog_Handler,
		},
		{
			MethodName: "FindExchangeLogs",
			Handler:    _ExchangeLogService_FindExchangeLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}
