// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logging-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ---------------------- << USER LOGS >>
type UserLog struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,3,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	Type                 string               `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Message              string               `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserLog) Reset()         { *m = UserLog{} }
func (m *UserLog) String() string { return proto.CompactTextString(m) }
func (*UserLog) ProtoMessage()    {}
func (*UserLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{0}
}

func (m *UserLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLog.Unmarshal(m, b)
}
func (m *UserLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLog.Marshal(b, m, deterministic)
}
func (m *UserLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLog.Merge(m, src)
}
func (m *UserLog) XXX_Size() int {
	return xxx_messageInfo_UserLog.Size(m)
}
func (m *UserLog) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLog.DiscardUnknown(m)
}

var xxx_messageInfo_UserLog proto.InternalMessageInfo

func (m *UserLog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserLog) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserLog) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *UserLog) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserLog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// CREATE
type CreateUserLogRequest struct {
	// API versioning
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UserLog              *UserLog `protobuf:"bytes,2,opt,name=userLog,proto3" json:"userLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserLogRequest) Reset()         { *m = CreateUserLogRequest{} }
func (m *CreateUserLogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserLogRequest) ProtoMessage()    {}
func (*CreateUserLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{1}
}

func (m *CreateUserLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserLogRequest.Unmarshal(m, b)
}
func (m *CreateUserLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserLogRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserLogRequest.Merge(m, src)
}
func (m *CreateUserLogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserLogRequest.Size(m)
}
func (m *CreateUserLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserLogRequest proto.InternalMessageInfo

func (m *CreateUserLogRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserLogRequest) GetUserLog() *UserLog {
	if m != nil {
		return m.UserLog
	}
	return nil
}

type CreateUserLogResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserLogResponse) Reset()         { *m = CreateUserLogResponse{} }
func (m *CreateUserLogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserLogResponse) ProtoMessage()    {}
func (*CreateUserLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{2}
}

func (m *CreateUserLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserLogResponse.Unmarshal(m, b)
}
func (m *CreateUserLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserLogResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserLogResponse.Merge(m, src)
}
func (m *CreateUserLogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserLogResponse.Size(m)
}
func (m *CreateUserLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserLogResponse proto.InternalMessageInfo

func (m *CreateUserLogResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserLogResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// READ
type ReadUserLogRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserLogRequest) Reset()         { *m = ReadUserLogRequest{} }
func (m *ReadUserLogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserLogRequest) ProtoMessage()    {}
func (*ReadUserLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{3}
}

func (m *ReadUserLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserLogRequest.Unmarshal(m, b)
}
func (m *ReadUserLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserLogRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserLogRequest.Merge(m, src)
}
func (m *ReadUserLogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserLogRequest.Size(m)
}
func (m *ReadUserLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserLogRequest proto.InternalMessageInfo

func (m *ReadUserLogRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadUserLogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadUserLogResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UserLog              *UserLog `protobuf:"bytes,2,opt,name=userLog,proto3" json:"userLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserLogResponse) Reset()         { *m = ReadUserLogResponse{} }
func (m *ReadUserLogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserLogResponse) ProtoMessage()    {}
func (*ReadUserLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{4}
}

func (m *ReadUserLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserLogResponse.Unmarshal(m, b)
}
func (m *ReadUserLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserLogResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserLogResponse.Merge(m, src)
}
func (m *ReadUserLogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserLogResponse.Size(m)
}
func (m *ReadUserLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserLogResponse proto.InternalMessageInfo

func (m *ReadUserLogResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadUserLogResponse) GetUserLog() *UserLog {
	if m != nil {
		return m.UserLog
	}
	return nil
}

// FIND LOGS
type FindUserLogsRequest struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	From                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	DeclarationId        int64                `protobuf:"varint,5,opt,name=declarationId,proto3" json:"declarationId,omitempty"`
	Type                 string               `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Limit                int32                `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32                `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindUserLogsRequest) Reset()         { *m = FindUserLogsRequest{} }
func (m *FindUserLogsRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserLogsRequest) ProtoMessage()    {}
func (*FindUserLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{5}
}

func (m *FindUserLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserLogsRequest.Unmarshal(m, b)
}
func (m *FindUserLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserLogsRequest.Marshal(b, m, deterministic)
}
func (m *FindUserLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserLogsRequest.Merge(m, src)
}
func (m *FindUserLogsRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserLogsRequest.Size(m)
}
func (m *FindUserLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserLogsRequest proto.InternalMessageInfo

func (m *FindUserLogsRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUserLogsRequest) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *FindUserLogsRequest) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *FindUserLogsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FindUserLogsRequest) GetDeclarationId() int64 {
	if m != nil {
		return m.DeclarationId
	}
	return 0
}

func (m *FindUserLogsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FindUserLogsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindUserLogsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type FindUserLogsResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	UserLogs             []*UserLog `protobuf:"bytes,2,rep,name=userLogs,proto3" json:"userLogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindUserLogsResponse) Reset()         { *m = FindUserLogsResponse{} }
func (m *FindUserLogsResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserLogsResponse) ProtoMessage()    {}
func (*FindUserLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fb7a78083aef92b, []int{6}
}

func (m *FindUserLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserLogsResponse.Unmarshal(m, b)
}
func (m *FindUserLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserLogsResponse.Marshal(b, m, deterministic)
}
func (m *FindUserLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserLogsResponse.Merge(m, src)
}
func (m *FindUserLogsResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserLogsResponse.Size(m)
}
func (m *FindUserLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserLogsResponse proto.InternalMessageInfo

func (m *FindUserLogsResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FindUserLogsResponse) GetUserLogs() []*UserLog {
	if m != nil {
		return m.UserLogs
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLog)(nil), "v1.UserLog")
	proto.RegisterType((*CreateUserLogRequest)(nil), "v1.CreateUserLogRequest")
	proto.RegisterType((*CreateUserLogResponse)(nil), "v1.CreateUserLogResponse")
	proto.RegisterType((*ReadUserLogRequest)(nil), "v1.ReadUserLogRequest")
	proto.RegisterType((*ReadUserLogResponse)(nil), "v1.ReadUserLogResponse")
	proto.RegisterType((*FindUserLogsRequest)(nil), "v1.FindUserLogsRequest")
	proto.RegisterType((*FindUserLogsResponse)(nil), "v1.FindUserLogsResponse")
}

func init() { proto.RegisterFile("logging-service.proto", fileDescriptor_1fb7a78083aef92b) }

var fileDescriptor_1fb7a78083aef92b = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0x26, 0xdb, 0xb7, 0xeb, 0xd4, 0x3b, 0x64, 0xae, 0x77, 0xae, 0xf9, 0x62, 0x08, 0x8a, 0x45,
	0x30, 0xc7, 0x55, 0x10, 0xfd, 0x22, 0x1c, 0x8a, 0x70, 0x20, 0x8a, 0x51, 0x7f, 0x40, 0xda, 0x4c,
	0xc3, 0x42, 0xd3, 0x8d, 0xd9, 0x6d, 0xc1, 0xcf, 0xfe, 0x30, 0x7f, 0x87, 0xff, 0x46, 0xb2, 0xd9,
	0x68, 0xd2, 0xa6, 0xf1, 0xbe, 0xed, 0x3c, 0xf3, 0xcc, 0xec, 0xcc, 0xb3, 0xcf, 0xc2, 0xc5, 0x5a,
	0x26, 0x89, 0xd8, 0x24, 0xcf, 0x15, 0xe5, 0x3b, 0xb1, 0xa4, 0x20, 0xcb, 0xa5, 0x96, 0xc8, 0x76,
	0xd7, 0xee, 0xa3, 0x44, 0xca, 0x64, 0x4d, 0x57, 0x06, 0x59, 0x6c, 0x57, 0x57, 0x5a, 0xa4, 0xa4,
	0x74, 0x94, 0x66, 0x25, 0xc9, 0xff, 0xe5, 0xc0, 0xe8, 0x9b, 0xa2, 0xfc, 0x83, 0x4c, 0xf0, 0x0c,
	0x98, 0x88, 0xb9, 0xe3, 0x39, 0xb3, 0x5e, 0xc8, 0x44, 0x8c, 0x97, 0x30, 0xdc, 0x2a, 0xca, 0x6f,
	0x63, 0xce, 0x0c, 0x66, 0x23, 0x7c, 0x0c, 0xa7, 0x31, 0x2d, 0xd7, 0x51, 0x1e, 0x69, 0x21, 0x37,
	0xb7, 0x31, 0xef, 0x99, 0x74, 0x13, 0x44, 0x84, 0xbe, 0xfe, 0x91, 0x11, 0xef, 0x7b, 0xce, 0x6c,
	0x1c, 0x9a, 0x33, 0x72, 0x18, 0xa5, 0xa4, 0x54, 0x94, 0x10, 0x1f, 0x18, 0xb8, 0x0a, 0xf1, 0x15,
	0x8c, 0x97, 0x39, 0x45, 0x9a, 0xe2, 0x1b, 0xcd, 0x87, 0x9e, 0x33, 0x9b, 0xcc, 0xdd, 0xa0, 0x1c,
	0x3e, 0xa8, 0x86, 0x0f, 0xbe, 0x56, 0xc3, 0x87, 0xff, 0xc8, 0xfe, 0x27, 0x98, 0xbe, 0x35, 0x81,
	0x5d, 0x23, 0xa4, 0xef, 0x5b, 0x52, 0x1a, 0xef, 0x43, 0x2f, 0xca, 0x84, 0x59, 0x67, 0x1c, 0x16,
	0x47, 0x7c, 0x02, 0xa3, 0x6d, 0xc9, 0x31, 0x0b, 0x4d, 0xe6, 0x93, 0x60, 0x77, 0x1d, 0x54, 0x65,
	0x55, 0xce, 0x7f, 0x0d, 0x17, 0x7b, 0x0d, 0x55, 0x26, 0x37, 0x8a, 0x5a, 0x3a, 0x96, 0x8a, 0xb1,
	0x4a, 0x31, 0xff, 0x25, 0x60, 0x48, 0x51, 0xfc, 0xdf, 0x49, 0xf6, 0xeb, 0x3e, 0xc2, 0x79, 0xa3,
	0xee, 0xe8, 0x85, 0x77, 0x5c, 0xe1, 0x27, 0x83, 0xf3, 0xf7, 0x62, 0x53, 0x35, 0x54, 0xc7, 0x27,
	0x09, 0xa0, 0xbf, 0xca, 0x65, 0x6a, 0xbb, 0x75, 0x49, 0x6e, 0x78, 0xf8, 0x0c, 0x98, 0x96, 0xe6,
	0xc1, 0xbb, 0xd9, 0x4c, 0xcb, 0x9a, 0x7f, 0xfa, 0xdd, 0xfe, 0x19, 0x74, 0xf9, 0x67, 0x58, 0xf3,
	0xcf, 0x14, 0x06, 0x6b, 0x91, 0x0a, 0xcd, 0x47, 0x9e, 0x33, 0x1b, 0x84, 0x65, 0x50, 0xdc, 0x23,
	0x57, 0x2b, 0x45, 0x9a, 0x9f, 0x18, 0xd8, 0x46, 0xfe, 0x67, 0x98, 0x36, 0x45, 0x38, 0x2a, 0xeb,
	0x53, 0x38, 0xb1, 0xd2, 0x29, 0xce, 0xbc, 0xde, 0xbe, 0xae, 0x7f, 0x93, 0xf3, 0xdf, 0x0e, 0x9c,
	0x59, 0xf4, 0x4b, 0xf9, 0xd9, 0xf0, 0x1d, 0x9c, 0x36, 0xec, 0x82, 0xbc, 0x28, 0x6d, 0xb3, 0xa4,
	0xfb, 0xb0, 0x25, 0x63, 0x67, 0x7a, 0x03, 0x93, 0x9a, 0x03, 0xf0, 0xb2, 0x60, 0x1e, 0x5a, 0xc9,
	0x7d, 0x70, 0x80, 0xdb, 0xfa, 0x1b, 0xb8, 0x57, 0xdf, 0x15, 0x0d, 0xb1, 0xc5, 0x02, 0x2e, 0x3f,
	0x4c, 0x94, 0x2d, 0x16, 0x43, 0xf3, 0x8c, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x36,
	0xcf, 0x45, 0x4f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserLogServiceClient is the client API for UserLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserLogServiceClient interface {
	CreateUserLog(ctx context.Context, in *CreateUserLogRequest, opts ...grpc.CallOption) (*CreateUserLogResponse, error)
	ReadUserLog(ctx context.Context, in *ReadUserLogRequest, opts ...grpc.CallOption) (*ReadUserLogResponse, error)
	FindUserLogs(ctx context.Context, in *FindUserLogsRequest, opts ...grpc.CallOption) (*FindUserLogsResponse, error)
}

type userLogServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserLogServiceClient(cc *grpc.ClientConn) UserLogServiceClient {
	return &userLogServiceClient{cc}
}

func (c *userLogServiceClient) CreateUserLog(ctx context.Context, in *CreateUserLogRequest, opts ...grpc.CallOption) (*CreateUserLogResponse, error) {
	out := new(CreateUserLogResponse)
	err := c.cc.Invoke(ctx, "/v1.UserLogService/CreateUserLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLogServiceClient) ReadUserLog(ctx context.Context, in *ReadUserLogRequest, opts ...grpc.CallOption) (*ReadUserLogResponse, error) {
	out := new(ReadUserLogResponse)
	err := c.cc.Invoke(ctx, "/v1.UserLogService/ReadUserLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLogServiceClient) FindUserLogs(ctx context.Context, in *FindUserLogsRequest, opts ...grpc.CallOption) (*FindUserLogsResponse, error) {
	out := new(FindUserLogsResponse)
	err := c.cc.Invoke(ctx, "/v1.UserLogService/FindUserLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLogServiceServer is the server API for UserLogService service.
type UserLogServiceServer interface {
	CreateUserLog(context.Context, *CreateUserLogRequest) (*CreateUserLogResponse, error)
	ReadUserLog(context.Context, *ReadUserLogRequest) (*ReadUserLogResponse, error)
	FindUserLogs(context.Context, *FindUserLogsRequest) (*FindUserLogsResponse, error)
}

func RegisterUserLogServiceServer(s *grpc.Server, srv UserLogServiceServer) {
	s.RegisterService(&_UserLogService_serviceDesc, srv)
}

func _UserLogService_CreateUserLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLogServiceServer).CreateUserLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserLogService/CreateUserLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLogServiceServer).CreateUserLog(ctx, req.(*CreateUserLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLogService_ReadUserLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLogServiceServer).ReadUserLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserLogService/ReadUserLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLogServiceServer).ReadUserLog(ctx, req.(*ReadUserLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLogService_FindUserLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLogServiceServer).FindUserLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserLogService/FindUserLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLogServiceServer).FindUserLogs(ctx, req.(*FindUserLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserLogService",
	HandlerType: (*UserLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserLog",
			Handler:    _UserLogService_CreateUserLog_Handler,
		},
		{
			MethodName: "ReadUserLog",
			Handler:    _UserLogService_ReadUserLog_Handler,
		},
		{
			MethodName: "FindUserLogs",
			Handler:    _UserLogService_FindUserLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging-service.proto",
}
