<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging-service.proto

namespace V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * CREATE
 *
 * Generated from protobuf message <code>v1.CreateUserLogRequest</code>
 */
class CreateUserLogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * API versioning
     *
     * Generated from protobuf field <code>string api = 1;</code>
     */
    private $api = '';
    /**
     * Generated from protobuf field <code>.v1.UserLog userLog = 2;</code>
     */
    private $userLog = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api
     *           API versioning
     *     @type \V1\UserLog $userLog
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LoggingService::initOnce();
        parent::__construct($data);
    }

    /**
     * API versioning
     *
     * Generated from protobuf field <code>string api = 1;</code>
     * @return string
     */
    public function getApi()
    {
        return $this->api;
    }

    /**
     * API versioning
     *
     * Generated from protobuf field <code>string api = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->api = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v1.UserLog userLog = 2;</code>
     * @return \V1\UserLog
     */
    public function getUserLog()
    {
        return $this->userLog;
    }

    /**
     * Generated from protobuf field <code>.v1.UserLog userLog = 2;</code>
     * @param \V1\UserLog $var
     * @return $this
     */
    public function setUserLog($var)
    {
        GPBUtil::checkMessage($var, \V1\UserLog::class);
        $this->userLog = $var;

        return $this;
    }

}

