<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging-service.proto

namespace V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v1.FindUserLogsResponse</code>
 */
class FindUserLogsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string api = 1;</code>
     */
    private $api = '';
    /**
     * Generated from protobuf field <code>repeated .v1.UserLog userLogs = 2;</code>
     */
    private $userLogs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api
     *     @type \V1\UserLog[]|\Google\Protobuf\Internal\RepeatedField $userLogs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LoggingService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string api = 1;</code>
     * @return string
     */
    public function getApi()
    {
        return $this->api;
    }

    /**
     * Generated from protobuf field <code>string api = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->api = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v1.UserLog userLogs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserLogs()
    {
        return $this->userLogs;
    }

    /**
     * Generated from protobuf field <code>repeated .v1.UserLog userLogs = 2;</code>
     * @param \V1\UserLog[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V1\UserLog::class);
        $this->userLogs = $arr;

        return $this;
    }

}

